package com.example.linuxapp.screens.kernel

import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun KprobesScreen(onBack: () -> Unit) {
    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        "kprobes",
                        color = Color(0xFF00FF41),
                        fontFamily = FontFamily.Monospace,
                        fontSize = 16.sp
                    )
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back", tint = Color.White)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = Color.Black)
            )
        },
        containerColor = Color.Black
    ) { innerPadding ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(horizontal = 16.dp),
            contentPadding = PaddingValues(vertical = 8.dp)
        ) {
            item {
                SectionCard(title = "What Is kprobes?") {
                    BodyText("kprobes is a Linux kernel mechanism that lets you place dynamic probes at nearly any kernel instruction at runtime — without rebooting, recompiling, or modifying the kernel source. Probes run a handler function when the probed instruction is reached.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("Three probe types:")
                    Spacer(modifier = Modifier.height(4.dp))
                    BodyText("• kprobe — hook any instruction; provides a pre_handler (before) and post_handler (after single-step).")
                    BodyText("• kretprobe — hook on function return; handler receives the return value.")
                    BodyText("• kprobe_multi (Linux 5.18+) — attach to many functions in one call using a name-pattern or address array.")
                }
            }
            item {
                SectionCard(title = "How kprobes Works (Brief)") {
                    BodyText("Three underlying mechanisms, used in priority order depending on kernel config:")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("1. Basic kprobes (int3 / #BP):")
                    BodyText("   The first byte of the target instruction is replaced with 0xCC (int3). When the CPU executes it, a #BP (breakpoint) exception fires. The kernel's kprobe exception handler calls your pre_handler, then restores and single-steps the original instruction using the x86 Trap Flag (TF). After the original instruction completes, post_handler is called. Overhead: ~100–300 ns per hit.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("2. Optimized kprobes — JMP to trampoline (CONFIG_OPTPROBES):")
                    BodyText("   When the target site has at least 5 bytes of room and meets safety requirements, kprobes replaces those bytes with a direct JMP to a generated trampoline stub. The trampoline runs pre_handler, then executes a saved copy of the displaced bytes, then returns. No exception is taken — this is significantly faster than the int3 path.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("3. ftrace-based kprobes (CONFIG_KPROBES_ON_FTRACE):")
                    BodyText("   If the target function has an ftrace NOP call site (as generated by -pg or -mfentry), kprobes piggybacks on ftrace's call patching instead of inserting int3. This has the lowest overhead of the three paths.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("For deeper internals — pt_regs layout, full LKM example, and blacklist details — see the Kernel Debugging screen.")
                }
            }
            item {
                SectionCard(title = "Can I Hook Any Function?") {
                    BodyText("Almost any function. Functions that are blacklisted cannot be probed:")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("• Functions marked __kprobes or __nokprobe_inline — these are inside the kprobe handler itself; probing them would cause infinite recursion.")
                    BodyText("• Functions marked notrace — typically used for critical path code or functions that must not be instrumented.")
                    BodyText("• Inlined functions — they have no independent symbol and no single address to probe. You must use an address offset instead of a name.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("Check at runtime:")
                    CodeBlock("""
                        |# Functions that cannot be probed
                        |cat /sys/kernel/debug/kprobes/blacklist
                        |
                        |# Currently active probes
                        |cat /sys/kernel/debug/kprobes/list
                        |# Format: address  type  symbol+offset  [module]
                        |# k = kprobe, r = kretprobe
                    """.trimMargin())
                }
            }
            item {
                SectionCard(title = "Accessing Function Parameters") {
                    BodyText("In a kprobe pre_handler, parameters are in struct pt_regs, reflecting the CPU register state at the probe point. Use the PT_REGS macros for portability across architectures:")
                    CodeBlock("""
                        |PT_REGS_PARM1(regs)   // 1st argument (RDI on x86-64)
                        |PT_REGS_PARM2(regs)   // 2nd argument (RSI)
                        |PT_REGS_PARM3(regs)   // 3rd argument (RDX)
                        |PT_REGS_PARM4(regs)   // 4th argument (RCX)
                        |PT_REGS_PARM5(regs)   // 5th argument (R8)
                        |PT_REGS_RC(regs)      // return value (RAX) — kretprobe
                    """.trimMargin())
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("Always cast to the expected type:")
                    CodeBlock("""
                        |static int pre(struct kprobe *p,
                        |               struct pt_regs *regs)
                        |{
                        |    struct file *f =
                        |        (struct file *)PT_REGS_PARM1(regs);
                        |    loff_t count =
                        |        (loff_t)PT_REGS_PARM3(regs);
                        |    pr_info("vfs_read: count=%lld\n",
                        |            (long long)count);
                        |    return 0;
                        |}
                    """.trimMargin())
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("For kretprobe, use the kretprobe_instance struct to access the return value. See PT_REGS_RC() or regs_return_value().")
                }
            }
            item {
                SectionCard(title = "Can I Skip the Original Function?") {
                    BodyText("Not with a plain kprobe returning 0 from pre_handler. Returning 1 from pre_handler is an internal implementation flag that skips the post_handler and single-step, but the original function still runs.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("To truly skip the function and force a return value, use override_function_with_return() together with regs_set_return_value() inside the pre_handler:")
                    CodeBlock("""
                        |static int pre(struct kprobe *p,
                        |               struct pt_regs *regs)
                        |{
                        |    regs_set_return_value(regs,
                        |                          (unsigned long)-EIO);
                        |    override_function_with_return(regs);
                        |    return 0;
                        |}
                    """.trimMargin())
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("For kretprobe, you can override the return value after the function has already executed by calling regs_set_return_value(ri->regs, newval) in the handler — the caller then sees newval instead of the real return.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("eBPF alternatives: bpf_override_return() from a kprobe BPF program (requires ALLOW_ERROR_INJECTION on target), or the fmod_ret program type (no annotation needed — see the Modify Return Value screen under eBPF).")
                }
            }
            item {
                SectionCard(title = "Multiple Hooks on the Same Function") {
                    BodyText("Yes — multiple kprobe structs can be registered on the same address at the same time. The kernel implements this through an \"aggregate\" kprobe that chains them.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("• All registered pre_handlers are called (order not guaranteed).")
                    BodyText("• All post_handlers are called (in reverse order from pre).")
                    BodyText("• Each probe is independent: registering or unregistering one does not affect the others.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("This allows multiple modules or eBPF programs to observe the same function simultaneously without conflicting.")
                }
            }
            item {
                SectionCard(title = "Removing Individual Probes") {
                    BodyText("Each probe can be removed independently using its own kprobe struct:")
                    CodeBlock("""
                        |// Remove a single kprobe
                        |unregister_kprobe(&my_kp);
                        |
                        |// Remove a kretprobe
                        |unregister_kretprobe(&my_krp);
                        |
                        |// Remove multiple at once (batch)
                        |struct kprobe *probes[] = { &kp1, &kp2, &kp3 };
                        |unregister_kprobes(probes, 3);
                    """.trimMargin())
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("After unregistration: the struct kprobe is safe to free or re-register. Any other probes on the same function continue working unaffected.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("You can also temporarily disable/re-enable without unregistering:")
                    CodeBlock("""
                        |disable_kprobe(&my_kp);   // stops calling handlers
                        |enable_kprobe(&my_kp);    // resumes
                    """.trimMargin())
                }
            }
            item {
                SectionCard(title = "Are There Races?") {
                    BodyText("Yes. Probe handlers can run on any CPU concurrently. The handler is your code, and it is your responsibility to make it SMP-safe.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("• If your handler accesses shared data, protect it with spinlocks or atomics.")
                    BodyText("• You cannot sleep in a kprobe pre_handler or post_handler — they run in interrupt-disabled context (basic kprobes) or at least in a context where sleeping is unsafe.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("kprobes itself handles the concurrent probe registration/unregistration safely — the internal data structures are protected.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("kretprobe and the maxactive field:")
                    CodeBlock("""
                        |struct kretprobe krp = {
                        |    .handler   = ret_handler,
                        |    .maxactive = 20,  // max concurrent instances
                        |    // default = max(10, 2*NR_CPUS)
                        |};
                    """.trimMargin())
                    BodyText("If more than maxactive goroutine instances are executing the function simultaneously, the probe is \"missed\" for the excess instances. The miss count is tracked in krp.nmissed.")
                }
            }
            item {
                SectionCard(title = "If I Place a Hook, Are Other Hooks Called?") {
                    BodyText("Yes. kprobes uses an aggregate model: all registered probes on the same address are chained and all handlers run.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("Unlike notifier chains (which can return NOTIFY_STOP to abort the chain), there is no mechanism to stop propagation to other kprobes. Each probe's handler runs regardless of what other handlers return.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("This means: if module A and module B both probe the same function, both handlers execute on every call. Neither can block the other.")
                }
            }
            item {
                SectionCard(title = "Is It Risky?") {
                    BodyText("Moderate risk. kprobes is a powerful tool but requires care:")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("• Probing a hotpath (e.g. __alloc_pages, schedule) adds per-call latency and can significantly slow the system.")
                    BodyText("• Probing the wrong address or a non-function boundary can corrupt instruction decode and crash the kernel.")
                    BodyText("• Recursive probing — if your handler calls a function that is also probed, and that probe calls back through the same path — kprobes detects this and skips the nested probe to avoid deadlock. Still, design your handler to call as few kernel functions as possible.")
                    BodyText("• Sleeping in a handler is unsafe: use pr_info/printk for logging, not alloc or mutex_lock.")
                    Spacer(modifier = Modifier.height(8.dp))
                    BodyText("Best practice: test kprobes on a QEMU/KVM VM (see the Kernel VM Debugging screen under Advanced Topics) before deploying on a real machine.")
                }
            }
            item {
                SectionCard(title = "Full Module Example") {
                    BodyText("Two probes on vfs_read: a pre_handler logging arguments, and a kretprobe logging the return value. Both are unregistered independently in module exit.")
                    CodeBlock("""
                        |#include <linux/kprobes.h>
                        |#include <linux/module.h>
                        |
                        |/* --- kprobe: pre_handler --- */
                        |static int pre_vfs_read(struct kprobe *p,
                        |                        struct pt_regs *regs)
                        |{
                        |    size_t count = (size_t)PT_REGS_PARM3(regs);
                        |    pr_info("vfs_read: count=%zu\n", count);
                        |    return 0;
                        |}
                        |
                        |static struct kprobe kp = {
                        |    .symbol_name = "vfs_read",
                        |    .pre_handler = pre_vfs_read,
                        |};
                        |
                        |/* --- kretprobe: return handler --- */
                        |static int ret_vfs_read(struct kretprobe_instance *ri,
                        |                        struct pt_regs *regs)
                        |{
                        |    long retval = regs_return_value(regs);
                        |    pr_info("vfs_read returned: %ld\n", retval);
                        |    return 0;
                        |}
                        |
                        |static struct kretprobe krp = {
                        |    .handler    = ret_vfs_read,
                        |    .kp.symbol_name = "vfs_read",
                        |    .maxactive  = 20,
                        |};
                        |
                        |static int __init kp_init(void)
                        |{
                        |    int r;
                        |    r = register_kprobe(&kp);
                        |    if (r) return r;
                        |    r = register_kretprobe(&krp);
                        |    if (r) { unregister_kprobe(&kp); return r; }
                        |    return 0;
                        |}
                        |
                        |static void __exit kp_exit(void)
                        |{
                        |    unregister_kprobe(&kp);
                        |    unregister_kretprobe(&krp);
                        |    pr_info("kretprobe missed: %d\n",
                        |            krp.nmissed);
                        |}
                        |
                        |module_init(kp_init);
                        |module_exit(kp_exit);
                        |MODULE_LICENSE("GPL");
                    """.trimMargin())
                }
            }
            item { Spacer(modifier = Modifier.height(24.dp)) }
        }
    }
}
