#!/usr/bin/env python3
"""Generate verbs.json for EP Portuguese conjugation app."""
import json

def ar_regular(inf, eng):
    s = inf[:-2]  # stem: fal
    return verb(inf, eng, "ar_regular", {
        "indicativoPresente": tc(s+"o",s+"as",s+"a",s+"amos",s+"ais",s+"am"),
        "indicativoPreteritoPerfeito": tc(s+"ei",s+"aste",s+"ou",s+"ámos",s+"astes",s+"aram"),
        "indicativoPreteritoImperfeito": tc(s+"ava",s+"avas",s+"ava",s+"ávamos",s+"áveis",s+"avam"),
        "indicativoPreteritoMaisQuePerfeito": tc(s+"ara",s+"aras",s+"ara",s+"áramos",s+"áreis",s+"aram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(s+"e",s+"es",s+"e",s+"emos",s+"eis",s+"em"),
        "conjuntivoPreteritoImperfeito": tc(s+"asse",s+"asses",s+"asse",s+"ássemos",s+"ásseis",s+"assem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,inf[:-2]+"armos",inf[:-2]+"ardes",inf[:-2]+"arem"),
        "imperativoAfirmativo": imp(s+"a",s+"e",s+"emos",s+"ai",s+"em"),
        "imperativoNegativo": impn(s+"es",s+"e",s+"emos",s+"eis",s+"em"),
    })

def ar_car(inf, eng):
    # c->qu before e; affects ConjPresente and PretPerf eu
    s = inf[:-2]; qs = s[:-1]+"qu"
    return verb(inf, eng, "ar_car", {
        "indicativoPresente": tc(s+"o",s+"as",s+"a",s+"amos",s+"ais",s+"am"),
        "indicativoPreteritoPerfeito": tc(qs+"ei",s+"aste",s+"ou",s+"ámos",s+"astes",s+"aram"),
        "indicativoPreteritoImperfeito": tc(s+"ava",s+"avas",s+"ava",s+"ávamos",s+"áveis",s+"avam"),
        "indicativoPreteritoMaisQuePerfeito": tc(s+"ara",s+"aras",s+"ara",s+"áramos",s+"áreis",s+"aram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(qs+"e",qs+"es",qs+"e",qs+"emos",qs+"eis",qs+"em"),
        "conjuntivoPreteritoImperfeito": tc(s+"asse",s+"asses",s+"asse",s+"ássemos",s+"ásseis",s+"assem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,s+"armos",s+"ardes",s+"arem"),
        "imperativoAfirmativo": imp(s+"a",qs+"e",qs+"emos",s+"ai",qs+"em"),
        "imperativoNegativo": impn(qs+"es",qs+"e",qs+"emos",qs+"eis",qs+"em"),
    })

def ar_gar(inf, eng):
    # g->gu before e
    s = inf[:-2]; gs = s+"u"
    return verb(inf, eng, "ar_gar", {
        "indicativoPresente": tc(s+"o",s+"as",s+"a",s+"amos",s+"ais",s+"am"),
        "indicativoPreteritoPerfeito": tc(gs+"ei",s+"aste",s+"ou",s+"ámos",s+"astes",s+"aram"),
        "indicativoPreteritoImperfeito": tc(s+"ava",s+"avas",s+"ava",s+"ávamos",s+"áveis",s+"avam"),
        "indicativoPreteritoMaisQuePerfeito": tc(s+"ara",s+"aras",s+"ara",s+"áramos",s+"áreis",s+"aram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(gs+"e",gs+"es",gs+"e",gs+"emos",gs+"eis",gs+"em"),
        "conjuntivoPreteritoImperfeito": tc(s+"asse",s+"asses",s+"asse",s+"ássemos",s+"ásseis",s+"assem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,s+"armos",s+"ardes",s+"arem"),
        "imperativoAfirmativo": imp(s+"a",gs+"e",gs+"emos",s+"ai",gs+"em"),
        "imperativoNegativo": impn(gs+"es",gs+"e",gs+"emos",gs+"eis",gs+"em"),
    })

def ar_çar(inf, eng):
    # ç->c before e (começar->começo, comece)
    s = inf[:-3]  # e.g. começ -> come
    sc = s+"ç"; cc = s+"c"
    return verb(inf, eng, "ar_çar", {
        "indicativoPresente": tc(sc+"o",sc+"as",sc+"a",sc+"amos",sc+"ais",sc+"am"),
        "indicativoPreteritoPerfeito": tc(cc+"ei",sc+"aste",sc+"ou",sc+"ámos",sc+"astes",sc+"aram"),
        "indicativoPreteritoImperfeito": tc(sc+"ava",sc+"avas",sc+"ava",sc+"ávamos",sc+"áveis",sc+"avam"),
        "indicativoPreteritoMaisQuePerfeito": tc(sc+"ara",sc+"aras",sc+"ara",sc+"áramos",sc+"áreis",sc+"aram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(cc+"e",cc+"es",cc+"e",cc+"emos",cc+"eis",cc+"em"),
        "conjuntivoPreteritoImperfeito": tc(sc+"asse",sc+"asses",sc+"asse",sc+"ássemos",sc+"ásseis",sc+"assem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,sc+"armos",sc+"ardes",sc+"arem"),
        "imperativoAfirmativo": imp(sc+"a",cc+"e",cc+"emos",sc+"ai",cc+"em"),
        "imperativoNegativo": impn(cc+"es",cc+"e",cc+"emos",cc+"eis",cc+"em"),
    })

def er_regular(inf, eng):
    s = inf[:-2]
    return verb(inf, eng, "er_regular", {
        "indicativoPresente": tc(s+"o",s+"es",s+"e",s+"emos",s+"eis",s+"em"),
        "indicativoPreteritoPerfeito": tc(s+"i",s+"este",s+"eu",s+"emos",s+"estes",s+"eram"),
        "indicativoPreteritoImperfeito": tc(s+"ia",s+"ias",s+"ia",s+"íamos",s+"íeis",s+"iam"),
        "indicativoPreteritoMaisQuePerfeito": tc(s+"era",s+"eras",s+"era",s+"êramos",s+"êreis",s+"eram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(s+"a",s+"as",s+"a",s+"amos",s+"ais",s+"am"),
        "conjuntivoPreteritoImperfeito": tc(s+"esse",s+"esses",s+"esse",s+"êssemos",s+"êsseis",s+"essem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,s+"ermos",s+"erdes",s+"erem"),
        "imperativoAfirmativo": imp(s+"e",s+"a",s+"amos",s+"ei",s+"am"),
        "imperativoNegativo": impn(s+"as",s+"a",s+"amos",s+"ais",s+"am"),
    })

def er_cer(inf, eng):
    # c->ç before a/o (conhecer->conheço)
    s = inf[:-3]; cs = s+"c"; çs = s+"ç"
    return verb(inf, eng, "er_cer", {
        "indicativoPresente": tc(çs+"o",cs+"es",cs+"e",cs+"emos",cs+"eis",cs+"em"),
        "indicativoPreteritoPerfeito": tc(cs+"i",cs+"este",cs+"eu",cs+"emos",cs+"estes",cs+"eram"),
        "indicativoPreteritoImperfeito": tc(cs+"ia",cs+"ias",cs+"ia",cs+"íamos",cs+"íeis",cs+"iam"),
        "indicativoPreteritoMaisQuePerfeito": tc(cs+"era",cs+"eras",cs+"era",cs+"êramos",cs+"êreis",cs+"eram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(çs+"a",çs+"as",çs+"a",çs+"amos",çs+"ais",çs+"am"),
        "conjuntivoPreteritoImperfeito": tc(cs+"esse",cs+"esses",cs+"esse",cs+"êssemos",cs+"êsseis",cs+"essem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,cs+"ermos",cs+"erdes",cs+"erem"),
        "imperativoAfirmativo": imp(cs+"e",çs+"a",çs+"amos",cs+"ei",çs+"am"),
        "imperativoNegativo": impn(çs+"as",çs+"a",çs+"amos",çs+"ais",çs+"am"),
    })

def ir_regular(inf, eng):
    s = inf[:-2]
    return verb(inf, eng, "ir_regular", {
        "indicativoPresente": tc(s+"o",s+"es",s+"e",s+"imos",s+"is",s+"em"),
        "indicativoPreteritoPerfeito": tc(s+"i",s+"iste",s+"iu",s+"imos",s+"istes",s+"iram"),
        "indicativoPreteritoImperfeito": tc(s+"ia",s+"ias",s+"ia",s+"íamos",s+"íeis",s+"iam"),
        "indicativoPreteritoMaisQuePerfeito": tc(s+"ira",s+"iras",s+"ira",s+"íramos",s+"íreis",s+"iram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(s+"a",s+"as",s+"a",s+"amos",s+"ais",s+"am"),
        "conjuntivoPreteritoImperfeito": tc(s+"isse",s+"isses",s+"isse",s+"íssemos",s+"ísseis",s+"issem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,s+"irmos",s+"irdes",s+"irem"),
        "imperativoAfirmativo": imp(s+"e",s+"a",s+"amos",s+"i",s+"am"),
        "imperativoNegativo": impn(s+"as",s+"a",s+"amos",s+"ais",s+"am"),
    })

def tc(eu,tu,ele,nos,vos,eles):
    return {"eu":eu,"tu":tu,"ele":ele,"nos":nos,"vos":vos,"eles":eles}

def imp(tu,ele,nos,vos,eles):
    return {"tu":tu,"ele":ele,"nos":nos,"vos":vos,"eles":eles}

def impn(tu,ele,nos,vos,eles):
    return {"tu":tu,"ele":ele,"nos":nos,"vos":vos,"eles":eles}

def verb(inf, eng, ctype, conjs):
    return {"infinitive":inf,"english":eng,"conjugationType":ctype,"conjugations":conjs}

# Manual irregular verbs
def manual(inf, eng, ctype, pres, pp, pimp, pmqp, fut, cond, cjpres, cjimp, cjfut, impaf, impneg):
    return verb(inf, eng, ctype, {
        "indicativoPresente": tc(*pres),
        "indicativoPreteritoPerfeito": tc(*pp),
        "indicativoPreteritoImperfeito": tc(*pimp),
        "indicativoPreteritoMaisQuePerfeito": tc(*pmqp),
        "indicativoFuturo": tc(*fut),
        "indicativoCondicional": tc(*cond),
        "conjuntivoPresente": tc(*cjpres),
        "conjuntivoPreteritoImperfeito": tc(*cjimp),
        "conjuntivoFuturo": tc(*cjfut),
        "imperativoAfirmativo": imp(*impaf),
        "imperativoNegativo": impn(*impneg),
    })

def ir_gj(inf, eng, pres1sg, pres_stem, conj_stem):
    """ir verbs with g->j: agir, corrigir, dirigir, atingir, fingir, fugir"""
    s = inf[:-2]
    pf = ir_regular(inf, eng)
    # override present 1sg and conjuntivo
    pf["conjugations"]["indicativoPresente"]["eu"] = pres1sg
    for k in ["eu","tu","ele","nos","vos","eles"]:
        suf = {"eu":"a","tu":"as","ele":"a","nos":"amos","vos":"ais","eles":"am"}[k]
        pf["conjugations"]["conjuntivoPresente"][k] = conj_stem+suf
    pf["conjugations"]["imperativoAfirmativo"]["ele"] = conj_stem+"a"
    pf["conjugations"]["imperativoAfirmativo"]["nos"] = conj_stem+"amos"
    pf["conjugations"]["imperativoAfirmativo"]["eles"] = conj_stem+"am"
    pf["conjugations"]["imperativoNegativo"] = {
        "tu":conj_stem+"as","ele":conj_stem+"a","nos":conj_stem+"amos","vos":conj_stem+"ais","eles":conj_stem+"am"
    }
    pf["conjugationType"] = "ir_irregular"
    return pf

def ir_echange(inf, eng, pres1sg, conj_stem):
    """ir verbs with e->i vowel change in 1sg present and conjuntivo (ferir, sentir, preferir etc)"""
    pf = ir_regular(inf, eng)
    pf["conjugations"]["indicativoPresente"]["eu"] = pres1sg
    for k in ["eu","tu","ele","nos","vos","eles"]:
        suf = {"eu":"a","tu":"as","ele":"a","nos":"amos","vos":"ais","eles":"am"}[k]
        pf["conjugations"]["conjuntivoPresente"][k] = conj_stem+suf
    pf["conjugations"]["imperativoAfirmativo"]["ele"] = conj_stem+"a"
    pf["conjugations"]["imperativoAfirmativo"]["nos"] = conj_stem+"amos"
    pf["conjugations"]["imperativoAfirmativo"]["eles"] = conj_stem+"am"
    pf["conjugations"]["imperativoNegativo"] = {
        "tu":conj_stem+"as","ele":conj_stem+"a","nos":conj_stem+"amos","vos":conj_stem+"ais","eles":conj_stem+"am"
    }
    pf["conjugationType"] = "ir_irregular"
    return pf

def duzir(inf, eng):
    """conduzir/produzir type: conduzo,conduzes,conduz,..."""
    s = inf[:-2]  # conduz
    return verb(inf, eng, "ir_irregular", {
        "indicativoPresente": tc(s+"o",s+"es",s[:-1],s+"imos",s+"is",s+"em"),
        "indicativoPreteritoPerfeito": tc(s+"i",s+"iste",s+"iu",s+"imos",s+"istes",s+"iram"),
        "indicativoPreteritoImperfeito": tc(s+"ia",s+"ias",s+"ia",s+"íamos",s+"íeis",s+"iam"),
        "indicativoPreteritoMaisQuePerfeito": tc(s+"ira",s+"iras",s+"ira",s+"íramos",s+"íreis",s+"iram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(s+"a",s+"as",s+"a",s+"amos",s+"ais",s+"am"),
        "conjuntivoPreteritoImperfeito": tc(s+"isse",s+"isses",s+"isse",s+"íssemos",s+"ísseis",s+"issem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,s+"irmos",s+"irdes",s+"irem"),
        "imperativoAfirmativo": imp(s[:-1],s+"a",s+"amos",s+"i",s+"am"),
        "imperativoNegativo": impn(s+"as",s+"a",s+"amos",s+"ais",s+"am"),
    })

def construir_type(inf, eng):
    s = inf[:-2]  # constru
    return verb(inf, eng, "ir_irregular", {
        "indicativoPresente": tc(s+"o",s+"ís",s+"i",s+"ímos",s+"ís",s+"em"),  # actually: construo,constróis,constrói...
        "indicativoPreteritoPerfeito": tc(s+"í",s+"íste",s+"iu",s+"ímos",s+"ístes",s+"íram"),
        "indicativoPreteritoImperfeito": tc(s+"ía",s+"ías",s+"ía",s+"íamos",s+"íeis",s+"íam"),
        "indicativoPreteritoMaisQuePerfeito": tc(s+"íra",s+"íras",s+"íra",s+"íramos",s+"íreis",s+"íram"),
        "indicativoFuturo": tc(inf+"ei",inf+"ás",inf+"á",inf+"emos",inf+"eis",inf+"ão"),
        "indicativoCondicional": tc(inf+"ia",inf+"ias",inf+"ia",inf+"íamos",inf+"íeis",inf+"iam"),
        "conjuntivoPresente": tc(s+"a",s+"as",s+"a",s+"amos",s+"ais",s+"am"),
        "conjuntivoPreteritoImperfeito": tc(s+"ísse",s+"ísses",s+"ísse",s+"íssemos",s+"ísseis",s+"íssem"),
        "conjuntivoFuturo": tc(inf,inf+"es",inf,s+"irmos",s+"irdes",s+"irem"),
        "imperativoAfirmativo": imp(s+"i",s+"a",s+"amos",s+"í",s+"am"),
        "imperativoNegativo": impn(s+"as",s+"a",s+"amos",s+"ais",s+"am"),
    })

verbs = [
    # ===== REGULAR -AR =====
    ar_regular("falar","to speak"),
    ar_regular("andar","to walk"),
    ar_regular("cantar","to sing"),
    ar_regular("trabalhar","to work"),
    ar_regular("gostar","to like"),
    ar_regular("usar","to use"),
    ar_regular("comprar","to buy"),
    ar_regular("mudar","to change"),
    ar_regular("entrar","to enter"),
    ar_regular("encontrar","to find/meet"),
    ar_regular("esperar","to wait/hope"),
    ar_regular("ganhar","to earn/win"),
    ar_regular("gastar","to spend"),
    ar_regular("levar","to take/carry"),
    ar_regular("olhar","to look at"),
    ar_regular("passar","to pass/spend"),
    ar_regular("perguntar","to ask"),
    ar_regular("precisar","to need"),
    ar_regular("tratar","to treat"),
    ar_regular("viajar","to travel"),
    ar_regular("visitar","to visit"),
    ar_regular("acabar","to finish"),
    ar_regular("ajudar","to help"),
    ar_regular("amar","to love"),
    ar_regular("apresentar","to present"),
    ar_regular("aumentar","to increase"),
    ar_regular("caminhar","to walk/hike"),
    ar_regular("celebrar","to celebrate"),
    ar_regular("cobrar","to charge/collect"),
    ar_regular("combinar","to agree/combine"),
    ar_regular("contar","to count/tell"),
    ar_regular("cortar","to cut"),
    ar_regular("criar","to create/raise"),
    ar_regular("cuidar","to care for"),
    ar_regular("deixar","to leave/let"),
    ar_regular("descansar","to rest"),
    ar_regular("desenhar","to draw"),
    ar_regular("desejar","to wish"),
    ar_regular("durar","to last"),
    ar_regular("ensinar","to teach"),
    ar_regular("errar","to make a mistake"),
    ar_regular("estudar","to study"),
    ar_regular("fechar","to close"),
    ar_regular("guardar","to keep/guard"),
    ar_regular("imaginar","to imagine"),
    ar_regular("lavar","to wash"),
    ar_regular("lembrar","to remember"),
    ar_regular("limpar","to clean"),
    ar_regular("mandar","to send/order"),
    ar_regular("melhorar","to improve"),
    ar_regular("misturar","to mix"),
    ar_regular("mostrar","to show"),
    ar_regular("nadar","to swim"),
    ar_regular("organizar","to organize"),
    ar_regular("parar","to stop"),
    ar_regular("pensar","to think"),
    ar_regular("preparar","to prepare"),
    ar_regular("provar","to try/taste/prove"),
    ar_regular("realizar","to achieve/realize"),
    ar_regular("reparar","to repair/notice"),
    ar_regular("respeitar","to respect"),
    ar_regular("roubar","to steal"),
    ar_regular("salvar","to save"),
    ar_regular("separar","to separate"),
    ar_regular("tentar","to try"),
    ar_regular("tirar","to remove/take"),
    ar_regular("tomar","to take/have"),
    ar_regular("treinar","to train"),
    ar_regular("voltar","to return"),
    ar_regular("chamar","to call"),
    ar_regular("deitar","to lay down"),
    ar_regular("gritar","to shout"),
    ar_regular("juntar","to join/gather"),
    ar_regular("levantar","to raise/get up"),
    ar_regular("morar","to live/reside"),
    ar_regular("notar","to notice"),
    ar_regular("ocupar","to occupy"),
    ar_regular("aceitar","to accept"),
    ar_regular("admirar","to admire"),
    ar_regular("afirmar","to affirm"),
    ar_regular("alimentar","to feed"),
    ar_regular("anunciar","to announce"),
    ar_regular("apoiar","to support"),
    ar_regular("arrumar","to tidy up"),
    ar_regular("assinar","to sign"),
    ar_regular("assustar","to scare"),
    ar_regular("comparar","to compare"),
    ar_regular("completar","to complete"),
    ar_regular("confirmar","to confirm"),
    ar_regular("consultar","to consult"),
    ar_regular("continuar","to continue"),
    ar_regular("controlar","to control"),
    ar_regular("conversar","to converse"),
    ar_regular("copiar","to copy"),
    ar_regular("declarar","to declare"),
    ar_regular("desculpar","to excuse"),
    ar_regular("espantar","to astonish"),
    ar_regular("plantar","to plant"),
    ar_regular("cozinhar","to cook"),
    ar_regular("cansar","to tire"),
    ar_regular("poupar","to save/economize"),
    ar_regular("aproximar","to approach"),
    ar_regular("trepar","to climb"),
    ar_regular("empurrar","to push"),
    ar_regular("puxar","to pull"),
    ar_regular("segurar","to hold/secure"),
    ar_regular("apertar","to tighten/press"),
    ar_regular("enganar","to deceive/trick"),
    # ===== -AR with orthographic change =====
    ar_car("explicar","to explain"),
    ar_car("tocar","to touch/play"),
    ar_car("ficar","to stay/become"),
    ar_car("buscar","to search for"),
    ar_car("marcar","to mark/schedule"),
    ar_car("colocar","to place/put"),
    ar_car("comunicar","to communicate"),
    ar_car("verificar","to verify"),
    ar_car("indicar","to indicate"),
    ar_car("fabricar","to manufacture"),
    ar_car("aplicar","to apply"),
    ar_car("brincar","to play/joke"),
    ar_gar("pagar","to pay"),
    ar_gar("chegar","to arrive"),
    ar_gar("jogar","to play sports"),
    ar_gar("ligar","to connect/call"),
    ar_gar("carregar","to carry/load"),
    ar_gar("navegar","to navigate"),
    ar_gar("negar","to deny"),
    ar_gar("obrigar","to oblige"),
    ar_gar("desligar","to disconnect/turn off"),
    ar_gar("apagar","to erase/turn off"),
    ar_çar("começar","to begin"),
    ar_çar("dançar","to dance"),
    ar_çar("alcançar","to reach"),
    ar_çar("avançar","to advance"),
    # ===== REGULAR -ER =====
    er_regular("beber","to drink"),
    er_regular("comer","to eat"),
    er_regular("vender","to sell"),
    er_regular("correr","to run"),
    er_regular("viver","to live"),
    er_regular("receber","to receive"),
    er_regular("sofrer","to suffer"),
    er_regular("meter","to put/insert"),
    er_regular("romper","to break/tear"),
    er_regular("escrever","to write"),
    er_regular("descrever","to describe"),
    er_regular("depender","to depend"),
    er_regular("aprender","to learn"),
    er_regular("compreender","to understand"),
    er_regular("responder","to respond"),
    er_regular("defender","to defend"),
    er_regular("suspender","to suspend"),
    er_regular("resolver","to solve"),
    er_regular("devolver","to return an item"),
    er_regular("envolver","to involve"),
    er_regular("mover","to move"),
    er_regular("absorver","to absorb"),
    # ===== -ER with c->ç =====
    er_cer("conhecer","to know a person"),
    er_cer("parecer","to seem"),
    er_cer("merecer","to deserve"),
    er_cer("crescer","to grow"),
    er_cer("oferecer","to offer"),
    er_cer("aparecer","to appear"),
    er_cer("desaparecer","to disappear"),
    er_cer("reconhecer","to recognize"),
    er_cer("estabelecer","to establish"),
    er_cer("pertencer","to belong"),
    er_cer("aquecer","to heat up"),
    er_cer("esquecer","to forget"),
    # ===== -ER IRREGULAR =====
    manual("perder","to lose","er_irregular",
        ("perco","perdes","perde","perdemos","perdeis","perdem"),
        ("perdi","perdeste","perdeu","perdemos","perdestes","perderam"),
        ("perdia","perdias","perdia","perdíamos","perdíeis","perdiam"),
        ("perdera","perderas","perdera","perdêramos","perdêreis","perderam"),
        ("perderei","perderás","perderá","perderemos","perdereis","perderão"),
        ("perderia","perderias","perderia","perderíamos","perderíeis","perderiam"),
        ("perca","percas","perca","percamos","percais","percam"),
        ("perdesse","perdesses","perdesse","perdêssemos","perdêsseis","perdessem"),
        ("perder","perderes","perder","perdermos","perderdes","perderem"),
        ("perde","perca","percamos","perdei","percam"),
        ("percas","perca","percamos","percais","percam"),
    ),
    manual("ler","to read","er_irregular",
        ("leio","lês","lê","lemos","ledes","lêem"),
        ("li","leste","leu","lemos","lestes","leram"),
        ("lia","lias","lia","líamos","líeis","liam"),
        ("lera","leras","lera","lêramos","lêreis","leram"),
        ("lerei","lerás","lerá","leremos","lereis","lerão"),
        ("leria","lerias","leria","leríamos","leríeis","leriam"),
        ("leia","leias","leia","leiamos","leiais","leiam"),
        ("lesse","lesses","lesse","lêssemos","lêsseis","lessem"),
        ("ler","leres","ler","lermos","lerdes","lerem"),
        ("lê","leia","leiamos","lede","leiam"),
        ("leias","leia","leiamos","leiais","leiam"),
    ),
    manual("ver","to see","er_irregular",
        ("vejo","vês","vê","vemos","vedes","vêem"),
        ("vi","viste","viu","vimos","vistes","viram"),
        ("via","vias","via","víamos","víeis","viam"),
        ("vira","viras","vira","víramos","víreis","viram"),
        ("verei","verás","verá","veremos","vereis","verão"),
        ("veria","verias","veria","veríamos","veríeis","veriam"),
        ("veja","vejas","veja","vejamos","vejais","vejam"),
        ("visse","visses","visse","víssemos","vísseis","vissem"),
        ("vir","vires","vir","virmos","virdes","virem"),
        ("vê","veja","vejamos","vede","vejam"),
        ("vejas","veja","vejamos","vejais","vejam"),
    ),
    manual("valer","to be worth","er_irregular",
        ("valho","vales","vale","valemos","valeis","valem"),
        ("vali","valeste","valeu","valemos","valestes","valeram"),
        ("valia","valias","valia","valíamos","valíeis","valiam"),
        ("valera","valeras","valera","valêramos","valêreis","valeram"),
        ("valerei","valerás","valerá","valeremos","valereis","valerão"),
        ("valeria","valerias","valeria","valeríamos","valeríeis","valeriam"),
        ("valha","valhas","valha","valhamos","valhais","valham"),
        ("valesse","valesses","valesse","valêssemos","valêsseis","valessem"),
        ("valer","valeres","valer","valermos","valerdes","valerem"),
        ("vale","valha","valhamos","valei","valham"),
        ("valhas","valha","valhamos","valhais","valham"),
    ),
    # ===== REGULAR -IR =====
    ir_regular("partir","to leave/break"),
    ir_regular("abrir","to open"),
    ir_regular("subir","to go up"),
    ir_regular("dividir","to divide"),
    ir_regular("existir","to exist"),
    ir_regular("insistir","to insist"),
    ir_regular("resistir","to resist"),
    ir_regular("assistir","to watch/attend"),
    ir_regular("discutir","to discuss"),
    ir_regular("permitir","to allow"),
    ir_regular("admitir","to admit"),
    ir_regular("emitir","to emit"),
    ir_regular("omitir","to omit"),
    ir_regular("transferir","to transfer"),
    ir_regular("progredir","to progress"),
    # ===== -IR IRREGULAR =====
    ir_echange("sentir","to feel","sinto","sint"),
    ir_echange("mentir","to lie","minto","mint"),
    ir_echange("ferir","to hurt","firo","fir"),
    ir_echange("preferir","to prefer","prefiro","prefir"),
    ir_echange("inserir","to insert","insiro","insir"),
    ir_echange("digerir","to digest","digiro","digir"),
    ir_echange("conferir","to check/confer","confiro","confir"),
    ir_echange("aderir","to adhere","adiro","adir"),
    ir_echange("referir","to refer","refiro","refir"),
    manual("dormir","to sleep","ir_irregular",
        ("durmo","dormes","dorme","dormimos","dormis","dormem"),
        ("dormi","dormiste","dormiu","dormimos","dormistes","dormiram"),
        ("dormia","dormias","dormia","dormíamos","dormíeis","dormiam"),
        ("dormira","dormiras","dormira","dormíramos","dormíreis","dormiram"),
        ("dormirei","dormirás","dormirá","dormiremos","dormireis","dormirão"),
        ("dormiria","dormirias","dormiria","dormiríamos","dormiríeis","dormiriam"),
        ("durma","durmas","durma","durmamos","durmais","durmam"),
        ("dormisse","dormisses","dormisse","dormíssemos","dormísseis","dormissem"),
        ("dormir","dormires","dormir","dormirmos","dormirdes","dormirem"),
        ("dorme","durma","durmamos","dormi","durmam"),
        ("durmas","durma","durmamos","durmais","durmam"),
    ),
    manual("cobrir","to cover","ir_irregular",
        ("cubro","cobres","cobre","cobrimos","cobris","cobrem"),
        ("cobri","cobriste","cobriu","cobrimos","cobristes","cobriram"),
        ("cobria","cobrias","cobria","cobríamos","cobríeis","cobriam"),
        ("cobrira","cobriras","cobrira","cobríramos","cobríreis","cobriram"),
        ("cobrirei","cobrirás","cobrirá","cobriremos","cobrireis","cobrirão"),
        ("cobriria","cobririas","cobriria","cobriríamos","cobriríeis","cobririam"),
        ("cubra","cubras","cubra","cubramos","cubrais","cubram"),
        ("cobrisse","cobrisses","cobrisse","cobríssemos","cobrísseis","cobrissem"),
        ("cobrir","cobrires","cobrir","cobrirmos","cobrirdes","cobrirem"),
        ("cobre","cubra","cubramos","cobri","cubram"),
        ("cubras","cubra","cubramos","cubrais","cubram"),
    ),
    manual("descobrir","to discover","ir_irregular",
        ("descubro","descobres","descobre","descobrimos","descobris","descobrem"),
        ("descobri","descobriste","descobriu","descobrimos","descobristes","descobriram"),
        ("descobria","descobrias","descobria","descobríamos","descobríeis","descobriam"),
        ("descobrira","descobriras","descobrira","descobríramos","descobríreis","descobriram"),
        ("descobrirei","descobrirás","descobrirá","descobriremos","descobrireis","descobrirão"),
        ("descobriria","descobririas","descobriria","descobriríamos","descobriríeis","descobririam"),
        ("descubra","descubras","descubra","descubramos","descubrais","descubram"),
        ("descobrisse","descobrisses","descobrisse","descobríssemos","descobrísseis","descobrissem"),
        ("descobrir","descobrires","descobrir","descobrirmos","descobrirdes","descobrirem"),
        ("descobre","descubra","descubramos","descobri","descubram"),
        ("descubras","descubra","descubramos","descubrais","descubram"),
    ),
    manual("seguir","to follow","ir_irregular",
        ("sigo","segues","segue","seguimos","seguis","seguem"),
        ("segui","seguiste","seguiu","seguimos","seguistes","seguiram"),
        ("seguia","seguias","seguia","seguíamos","seguíeis","seguiam"),
        ("seguira","seguiras","seguira","seguíramos","seguíreis","seguiram"),
        ("seguirei","seguirás","seguirá","seguiremos","seguireis","seguirão"),
        ("seguiria","seguirias","seguiria","seguiríamos","seguiríeis","seguiriam"),
        ("siga","sigas","siga","sigamos","sigais","sigam"),
        ("seguisse","seguisses","seguisse","seguíssemos","seguísseis","seguissem"),
        ("seguir","seguires","seguir","seguirmos","seguirdes","seguirem"),
        ("segue","siga","sigamos","segui","sigam"),
        ("sigas","siga","sigamos","sigais","sigam"),
    ),
    manual("pedir","to ask for","ir_irregular",
        ("peço","pedes","pede","pedimos","pedis","pedem"),
        ("pedi","pediste","pediu","pedimos","pedistes","pediram"),
        ("pedia","pedias","pedia","pedíamos","pedíeis","pediam"),
        ("pedira","pediras","pedira","pedíramos","pedíreis","pediram"),
        ("pedirei","pedirás","pedirá","pediremos","pedireis","pedirão"),
        ("pediria","pedirias","pediria","pediríamos","pediríeis","pediriam"),
        ("peça","peças","peça","peçamos","peçais","peçam"),
        ("pedisse","pedisses","pedisse","pedíssemos","pedísseis","pedissem"),
        ("pedir","pedires","pedir","pedirmos","pedirdes","pedirem"),
        ("pede","peça","peçamos","pedi","peçam"),
        ("peças","peça","peçamos","peçais","peçam"),
    ),
    manual("ouvir","to hear","ir_irregular",
        ("ouço","ouves","ouve","ouvimos","ouvis","ouvem"),
        ("ouvi","ouviste","ouviu","ouvimos","ouvistes","ouviram"),
        ("ouvia","ouvias","ouvia","ouvíamos","ouvíeis","ouviam"),
        ("ouvira","ouviras","ouvira","ouvíramos","ouvíreis","ouviram"),
        ("ouvirei","ouvirás","ouvirá","ouviremos","ouvireis","ouvirão"),
        ("ouviria","ouvirias","ouviria","ouviríamos","ouviríeis","ouviriam"),
        ("ouça","ouças","ouça","ouçamos","ouçais","ouçam"),
        ("ouvisse","ouvisses","ouvisse","ouvíssemos","ouvísseis","ouvissem"),
        ("ouvir","ouvires","ouvir","ouvirmos","ouvirdes","ouvirem"),
        ("ouve","ouça","ouçamos","ouvi","ouçam"),
        ("ouças","ouça","ouçamos","ouçais","ouçam"),
    ),
    ir_gj("agir","to act","ajo","ag","aj"),
    ir_gj("corrigir","to correct","corrijo","corrig","corrij"),
    ir_gj("dirigir","to direct/drive","dirijo","dirig","dirij"),
    ir_gj("exigir","to demand","exijo","exig","exij"),
    ir_gj("atingir","to reach/attain","atinjo","ating","atinj"),
    ir_gj("fingir","to pretend","finjo","fing","finj"),
    ir_gj("fugir","to flee","fujo","fug","fuj"),
    ir_gj("surgir","to emerge","surjo","surg","surj"),
    duzir("conduzir","to drive/conduct"),
    duzir("produzir","to produce"),
    duzir("traduzir","to translate"),
    duzir("introduzir","to introduce"),
    duzir("reduzir","to reduce"),
    manual("rir","to laugh","ir_irregular",
        ("rio","ris","ri","rimos","rides","riem"),
        ("ri","riste","riu","rimos","ristes","riram"),
        ("ria","rias","ria","ríamos","ríeis","riam"),
        ("rira","riras","rira","ríramos","ríreis","riram"),
        ("rirei","rirás","rirá","riremos","rireis","rirão"),
        ("riria","ririas","riria","riríamos","riríeis","ririam"),
        ("ria","rias","ria","riamos","riais","riam"),
        ("risse","risses","risse","ríssemos","rísseis","rissem"),
        ("rir","rires","rir","rirmos","rirdes","rirem"),
        ("ri","ria","riamos","ride","riam"),
        ("rias","ria","riamos","riais","riam"),
    ),
    manual("sorrir","to smile","ir_irregular",
        ("sorrio","sorris","sorri","sorrimos","sorrides","sorriem"),
        ("sorri","sorriste","sorriu","sorrimos","sorristes","sorriram"),
        ("sorria","sorrias","sorria","sorríamos","sorríeis","sorriam"),
        ("sorrira","sorriras","sorrira","sorríramos","sorríreis","sorriram"),
        ("sorrirei","sorrirás","sorrirá","sorriremos","sorrireis","sorrirão"),
        ("sorriria","sorririas","sorriria","sorriríamos","sorriríeis","sorrirjam"),
        ("sorria","sorrias","sorria","sorriamos","sorriais","sorriam"),
        ("sorrisse","sorrisses","sorrisse","sorríssemos","sorrísseis","sorrissem"),
        ("sorrir","sorrires","sorrir","sorrirmos","sorrirdes","sorrirem"),
        ("sorri","sorria","sorriamos","sorride","sorriam"),
        ("sorrias","sorria","sorriamos","sorriais","sorriam"),
    ),
    construir_type("construir","to build"),
    construir_type("destruir","to destroy"),
    construir_type("incluir","to include"),
    construir_type("excluir","to exclude"),
    construir_type("contribuir","to contribute"),
    construir_type("distribuir","to distribute"),
    # ===== HIGHLY IRREGULAR =====
    manual("ser","to be (permanent)","irregular",
        ("sou","és","é","somos","sois","são"),
        ("fui","foste","foi","fomos","fostes","foram"),
        ("era","eras","era","éramos","éreis","eram"),
        ("fora","foras","fora","fôramos","fôreis","foram"),
        ("serei","serás","será","seremos","sereis","serão"),
        ("seria","serias","seria","seríamos","seríeis","seriam"),
        ("seja","sejas","seja","sejamos","sejais","sejam"),
        ("fosse","fosses","fosse","fôssemos","fôsseis","fossem"),
        ("for","fores","for","formos","fordes","forem"),
        ("sê","seja","sejamos","sede","sejam"),
        ("sejas","seja","sejamos","sejais","sejam"),
    ),
    manual("estar","to be (temporary)","irregular",
        ("estou","estás","está","estamos","estais","estão"),
        ("estive","estiveste","esteve","estivemos","estivestes","estiveram"),
        ("estava","estavas","estava","estávamos","estáveis","estavam"),
        ("estivera","estiveras","estivera","estivêramos","estivêreis","estiveram"),
        ("estarei","estarás","estará","estaremos","estareis","estarão"),
        ("estaria","estarias","estaria","estaríamos","estaríeis","estariam"),
        ("esteja","estejas","esteja","estejamos","estejais","estejam"),
        ("estivesse","estivesses","estivesse","estivêssemos","estivêsseis","estivessem"),
        ("estiver","estiveres","estiver","estivermos","estiverdes","estiverem"),
        ("está","esteja","estejamos","estai","estejam"),
        ("estejas","esteja","estejamos","estejais","estejam"),
    ),
    manual("ter","to have","irregular",
        ("tenho","tens","tem","temos","tendes","têm"),
        ("tive","tiveste","teve","tivemos","tivestes","tiveram"),
        ("tinha","tinhas","tinha","tínhamos","tínheis","tinham"),
        ("tivera","tiveras","tivera","tivêramos","tivêreis","tiveram"),
        ("terei","terás","terá","teremos","tereis","terão"),
        ("teria","terias","teria","teríamos","teríeis","teriam"),
        ("tenha","tenhas","tenha","tenhamos","tenhais","tenham"),
        ("tivesse","tivesses","tivesse","tivêssemos","tivêsseis","tivessem"),
        ("tiver","tiveres","tiver","tivermos","tiverdes","tiverem"),
        ("tem","tenha","tenhamos","tende","tenham"),
        ("tenhas","tenha","tenhamos","tenhais","tenham"),
    ),
    manual("haver","to have/there is","irregular",
        ("hei","hás","há","havemos","haveis","hão"),
        ("houve","houveste","houve","houvemos","houvestes","houveram"),
        ("havia","havias","havia","havíamos","havíeis","haviam"),
        ("houvera","houveras","houvera","houvêramos","houvêreis","houveram"),
        ("haverei","haverás","haverá","haveremos","havereis","haverão"),
        ("haveria","haverias","haveria","haveríamos","haveríeis","haveriam"),
        ("haja","hajas","haja","hajamos","hajais","hajam"),
        ("houvesse","houvesses","houvesse","houvêssemos","houvêsseis","houvessem"),
        ("houver","houveres","houver","houvermos","houverdes","houverem"),
        ("há","haja","hajamos","havei","hajam"),
        ("hajas","haja","hajamos","hajais","hajam"),
    ),
    manual("ir","to go","irregular",
        ("vou","vais","vai","vamos","ides","vão"),
        ("fui","foste","foi","fomos","fostes","foram"),
        ("ia","ias","ia","íamos","íeis","iam"),
        ("fora","foras","fora","fôramos","fôreis","foram"),
        ("irei","irás","irá","iremos","ireis","irão"),
        ("iria","irias","iria","iríamos","iríeis","iriam"),
        ("vá","vás","vá","vamos","vades","vão"),
        ("fosse","fosses","fosse","fôssemos","fôsseis","fossem"),
        ("for","fores","for","formos","fordes","forem"),
        ("vai","vá","vamos","ide","vão"),
        ("vás","vá","vamos","vades","vão"),
    ),
    manual("vir","to come","irregular",
        ("venho","vens","vem","vimos","vindes","vêm"),
        ("vim","vieste","veio","viemos","viestes","vieram"),
        ("vinha","vinhas","vinha","vínhamos","vínheis","vinham"),
        ("viera","vieras","viera","viêramos","viêreis","vieram"),
        ("virei","virás","virá","viremos","vireis","virão"),
        ("viria","virias","viria","viríamos","viríeis","viriam"),
        ("venha","venhas","venha","venhamos","venhais","venham"),
        ("viesse","viesses","viesse","viêssemos","viêsseis","viessem"),
        ("vier","vieres","vier","viermos","vierdes","vierem"),
        ("vem","venha","venhamos","vinde","venham"),
        ("venhas","venha","venhamos","venhais","venham"),
    ),
    manual("fazer","to do/make","irregular",
        ("faço","fazes","faz","fazemos","fazeis","fazem"),
        ("fiz","fizeste","fez","fizemos","fizestes","fizeram"),
        ("fazia","fazias","fazia","fazíamos","fazíeis","faziam"),
        ("fizera","fizeras","fizera","fizêramos","fizêreis","fizeram"),
        ("farei","farás","fará","faremos","fareis","farão"),
        ("faria","farias","faria","faríamos","faríeis","fariam"),
        ("faça","faças","faça","façamos","façais","façam"),
        ("fizesse","fizesses","fizesse","fizêssemos","fizêsseis","fizessem"),
        ("fizer","fizeres","fizer","fizermos","fizerdes","fizerem"),
        ("faz","faça","façamos","fazei","façam"),
        ("faças","faça","façamos","façais","façam"),
    ),
    manual("poder","can/to be able","irregular",
        ("posso","podes","pode","podemos","podeis","podem"),
        ("pude","pudeste","pôde","pudemos","pudestes","puderam"),
        ("podia","podias","podia","podíamos","podíeis","podiam"),
        ("pudera","puderas","pudera","pudêramos","pudêreis","puderam"),
        ("poderei","poderás","poderá","poderemos","podereis","poderão"),
        ("poderia","poderias","poderia","poderíamos","poderíeis","poderiam"),
        ("possa","possas","possa","possamos","possais","possam"),
        ("pudesse","pudesses","pudesse","pudêssemos","pudêsseis","pudessem"),
        ("puder","puderes","puder","pudermos","puderdes","puderem"),
        ("pode","possa","possamos","podei","possam"),
        ("possas","possa","possamos","possais","possam"),
    ),
    manual("querer","to want","irregular",
        ("quero","queres","quer","queremos","quereis","querem"),
        ("quis","quiseste","quis","quisemos","quisestes","quiseram"),
        ("queria","querias","queria","queríamos","queríeis","queriam"),
        ("quisera","quiseras","quisera","quisêramos","quisêreis","quiseram"),
        ("quererei","quererás","quererá","quereremos","querereis","quererão"),
        ("quereria","quererias","quereria","quereríamos","quereríeis","quereriam"),
        ("queira","queiras","queira","queiramos","queirais","queiram"),
        ("quisesse","quisesses","quisesse","quisêssemos","quisêsseis","quisessem"),
        ("quiser","quiseres","quiser","quisermos","quiserdes","quiserem"),
        ("quer","queira","queiramos","querei","queiram"),
        ("queiras","queira","queiramos","queirais","queiram"),
    ),
    manual("saber","to know a fact","irregular",
        ("sei","sabes","sabe","sabemos","sabeis","sabem"),
        ("soube","soubeste","soube","soubemos","soubestes","souberam"),
        ("sabia","sabias","sabia","sabíamos","sabíeis","sabiam"),
        ("soubera","souberas","soubera","soubêramos","soubêreis","souberam"),
        ("saberei","saberás","saberá","saberemos","sabereis","saberão"),
        ("saberia","saberias","saberia","saberíamos","saberíeis","saberiam"),
        ("saiba","saibas","saiba","saibamos","saibais","saibam"),
        ("soubesse","soubesses","soubesse","soubêssemos","soubêsseis","soubessem"),
        ("souber","souberes","souber","soubermos","souberdes","souberem"),
        ("sabe","saiba","saibamos","sabei","saibam"),
        ("saibas","saiba","saibamos","saibais","saibam"),
    ),
    manual("dar","to give","irregular",
        ("dou","dás","dá","damos","dais","dão"),
        ("dei","deste","deu","demos","destes","deram"),
        ("dava","davas","dava","dávamos","dáveis","davam"),
        ("dera","deras","dera","dêramos","dêreis","deram"),
        ("darei","darás","dará","daremos","dareis","darão"),
        ("daria","darias","daria","daríamos","daríeis","dariam"),
        ("dê","dês","dê","demos","deis","deem"),
        ("desse","desses","desse","dêssemos","dêsseis","dessem"),
        ("der","deres","der","dermos","derdes","derem"),
        ("dá","dê","demos","dai","deem"),
        ("dês","dê","demos","deis","deem"),
    ),
    manual("trazer","to bring","irregular",
        ("trago","trazes","traz","trazemos","trazeis","trazem"),
        ("trouxe","trouxeste","trouxe","trouxemos","trouxestes","trouxeram"),
        ("trazia","trazias","trazia","trazíamos","trazíeis","traziam"),
        ("trouxera","trouxeras","trouxera","trouxêramos","trouxêreis","trouxeram"),
        ("trarei","trarás","trará","traremos","trareis","trarão"),
        ("traria","trarias","traria","traríamos","traríeis","trariam"),
        ("traga","tragas","traga","tragamos","tragais","tragam"),
        ("trouxesse","trouxesses","trouxesse","trouxêssemos","trouxêsseis","trouxessem"),
        ("trouxer","trouxeres","trouxer","trouxermos","trouxerdes","trouxerem"),
        ("traz","traga","tragamos","trazei","tragam"),
        ("tragas","traga","tragamos","tragais","tragam"),
    ),
    manual("dizer","to say/tell","irregular",
        ("digo","dizes","diz","dizemos","dizeis","dizem"),
        ("disse","disseste","disse","dissemos","dissestes","disseram"),
        ("dizia","dizias","dizia","dizíamos","dizíeis","diziam"),
        ("dissera","disseras","dissera","dissêramos","dissêreis","disseram"),
        ("direi","dirás","dirá","diremos","direis","dirão"),
        ("diria","dirias","diria","diríamos","diríeis","diriam"),
        ("diga","digas","diga","digamos","digais","digam"),
        ("dissesse","dissesses","dissesse","dissêssemos","dissêsseis","dissessem"),
        ("disser","disseres","disser","dissermos","disserdes","disserem"),
        ("diz","diga","digamos","dizei","digam"),
        ("digas","diga","digamos","digais","digam"),
    ),
    manual("pôr","to put/place","irregular",
        ("ponho","pões","põe","pomos","pondes","põem"),
        ("pus","puseste","pôs","pusemos","pusestes","puseram"),
        ("punha","punhas","punha","púnhamos","púnheis","punham"),
        ("pusera","puseras","pusera","pusêramos","pusêreis","puseram"),
        ("porei","porás","porá","poremos","poreis","porão"),
        ("poria","porias","poria","poríamos","poríeis","poriam"),
        ("ponha","ponhas","ponha","ponhamos","ponhais","ponham"),
        ("pusesse","pusesses","pusesse","pusêssemos","pusêsseis","pusessem"),
        ("puser","puseres","puser","pusermos","puserdes","puserem"),
        ("põe","ponha","ponhamos","ponde","ponham"),
        ("ponhas","ponha","ponhamos","ponhais","ponham"),
    ),
    manual("caber","to fit","irregular",
        ("caibo","cabes","cabe","cabemos","cabeis","cabem"),
        ("coube","coubeste","coube","coubemos","coubestes","couberam"),
        ("cabia","cabias","cabia","cabíamos","cabíeis","cabiam"),
        ("coubera","couberas","coubera","coubêramos","coubêreis","couberam"),
        ("caberei","caberás","caberá","caberemos","cabereis","caberão"),
        ("caberia","caberias","caberia","caberíamos","caberíeis","caberiam"),
        ("caiba","caibas","caiba","caibamos","caibais","caibam"),
        ("coubesse","coubesses","coubesse","coubêssemos","coubêsseis","coubessem"),
        ("couber","couberes","couber","coubermos","couberdes","couberem"),
        ("cabe","caiba","caibamos","cabei","caibam"),
        ("caibas","caiba","caibamos","caibais","caibam"),
    ),
    manual("cair","to fall","irregular",
        ("caio","cais","cai","caímos","caís","caem"),
        ("caí","caíste","caiu","caímos","caístes","caíram"),
        ("caía","caías","caía","caíamos","caíeis","caíam"),
        ("caíra","caíras","caíra","caíramos","caíreis","caíram"),
        ("cairei","cairás","cairá","cairemos","caireis","cairão"),
        ("cairia","cairias","cairia","cairíamos","cairíeis","cairiam"),
        ("caia","caias","caia","caiamos","caiais","caiam"),
        ("caísse","caísses","caísse","caíssemos","caísseis","caíssem"),
        ("cair","caíres","cair","cairmos","cairdes","caírem"),
        ("cai","caia","caiamos","caí","caiam"),
        ("caias","caia","caiamos","caiais","caiam"),
    ),
    manual("sair","to go out","irregular",
        ("saio","sais","sai","saímos","saís","saem"),
        ("saí","saíste","saiu","saímos","saístes","saíram"),
        ("saía","saías","saía","saíamos","saíeis","saíam"),
        ("saíra","saíras","saíra","saíramos","saíreis","saíram"),
        ("sairei","sairás","sairá","sairemos","saireis","sairão"),
        ("sairia","sairias","sairia","sairíamos","sairíeis","sairiam"),
        ("saia","saias","saia","saiamos","saiais","saiam"),
        ("saísse","saísses","saísse","saíssemos","saísseis","saíssem"),
        ("sair","saíres","sair","sairmos","sairdes","saírem"),
        ("sai","saia","saiamos","saí","saiam"),
        ("saias","saia","saiamos","saiais","saiam"),
    ),
    manual("manter","to maintain","irregular",
        ("mantenho","manténs","mantém","mantemos","mantendes","mantêm"),
        ("mantive","mantiveste","manteve","mantivemos","mantivestes","mantiveram"),
        ("mantinha","mantinhas","mantinha","mantínhamos","mantínheis","mantinham"),
        ("mantivera","mantiveras","mantivera","mantivêramos","mantivêreis","mantiveram"),
        ("manterei","manterás","manterá","manteremos","mantereis","manterão"),
        ("manteria","manterias","manteria","manteríamos","manteríeis","manteriam"),
        ("mantenha","mantenhas","mantenha","mantenhamos","mantenhais","mantenham"),
        ("mantivesse","mantivesses","mantivesse","mantivêssemos","mantivêsseis","mantivessem"),
        ("mantiver","mantiveres","mantiver","mantivermos","mantiverdes","mantiverem"),
        ("mantém","mantenha","mantenhamos","mantende","mantenham"),
        ("mantenhas","mantenha","mantenhamos","mantenhais","mantenham"),
    ),
    manual("obter","to obtain","irregular",
        ("obtenho","obténs","obtém","obtemos","obtendes","obtêm"),
        ("obtive","obtiveste","obteve","obtivemos","obtivestes","obtiveram"),
        ("obtinha","obtinhas","obtinha","obtínhamos","obtínheis","obtinham"),
        ("obtivera","obtiveras","obtivera","obtivêramos","obtivêreis","obtiveram"),
        ("obterei","obterás","obterá","obteremos","obtereis","obterão"),
        ("obteria","obterias","obteria","obteríamos","obteríeis","obteriam"),
        ("obtenha","obtenhas","obtenha","obtenhamos","obtenhais","obtenham"),
        ("obtivesse","obtivesses","obtivesse","obtivêssemos","obtivêsseis","obtivessem"),
        ("obtiver","obtiveres","obtiver","obtivermos","obtiverdes","obtiverem"),
        ("obtém","obtenha","obtenhamos","obtende","obtenham"),
        ("obtenhas","obtenha","obtenhamos","obtenhais","obtenham"),
    ),
    manual("conter","to contain","irregular",
        ("contenho","conténs","contém","contemos","contendes","contêm"),
        ("contive","contiveste","conteve","contivemos","contivestes","contiveram"),
        ("continha","continhas","continha","contínhamos","contínheis","continham"),
        ("contivera","contiveras","contivera","contivêramos","contivêreis","contiveram"),
        ("conterei","conterás","conterá","conteremos","contereis","conterão"),
        ("conteria","conterias","conteria","conteríamos","conteríeis","conteriam"),
        ("contenha","contenhas","contenha","contenhamos","contenhais","contenham"),
        ("contivesse","contivesses","contivesse","contivêssemos","contivêsseis","contivessem"),
        ("contiver","contiveres","contiver","contivermos","contiverdes","contiverem"),
        ("contém","contenha","contenhamos","contende","contenham"),
        ("contenhas","contenha","contenhamos","contenhais","contenham"),
    ),
    manual("intervir","to intervene","irregular",
        ("intervenho","intervéns","intervém","intervimos","intervindes","intervêm"),
        ("intervim","intervieste","interveio","interviemos","interviestes","intervieram"),
        ("intervinha","intervinhas","intervinha","intervínhamos","intervínheis","intervinham"),
        ("interviera","intervieras","interviera","interviêramos","interviêreis","intervieram"),
        ("intervirei","intervirás","intervirá","interviremos","intervireis","intervirão"),
        ("interviria","intervirias","interviria","interviríamos","interviríeis","interviriam"),
        ("intervenha","intervenhas","intervenha","intervenhamos","intervenhais","intervenham"),
        ("interviesse","interviesses","interviesse","interviêssemos","interviêsseis","interviessem"),
        ("interviér","interviéres","interviér","interviermos","intervierdes","intervierem"),
        ("intervém","intervenha","intervenhamos","intervinde","intervenham"),
        ("intervenhas","intervenha","intervenhamos","intervenhais","intervenham"),
    ),
    manual("prevenir","to prevent","irregular",
        ("prevenho","prevéns","prevém","prevenimos","prevenides","prevêm"),
        ("preveni","preveniste","preveniu","prevenimos","prevenistes","preveniram"),
        ("prevenia","prevenias","prevenia","prevníamos","prevníeis","preveniam"),
        ("prevenira","preveniras","prevenira","preveníramos","preveníreis","preveniram"),
        ("prevenirei","prevenirás","prevenirá","preveniremos","prevenireis","prevenirão"),
        ("preveniria","prevenirias","preveniria","preveniríamos","preveniríeis","preveniriam"),
        ("prevenha","prevenhas","prevenha","prevenhamos","prevenhais","prevenham"),
        ("prevenisse","prevenisses","prevenisse","preveníssemos","prevenísseis","prevenissem"),
        ("prevenir","prevenires","prevenir","prevenirmos","prevenirdes","prevenirem"),
        ("prevém","prevenha","prevenhamos","preveni","prevenham"),
        ("prevenhas","prevenha","prevenhamos","prevenhais","prevenham"),
    ),
    manual("prever","to foresee","er_irregular",
        ("prevejo","prevês","prevê","prevemos","prevedes","prevêem"),
        ("previ","previste","previu","previmos","previstes","previram"),
        ("previa","previas","previa","prevíamos","prevíeis","previam"),
        ("previra","previras","previra","prevíramos","prevíreis","previram"),
        ("preverei","preverás","preverá","preveremos","prevereis","preverão"),
        ("preveria","preverias","preveria","preveríamos","preveríeis","preveriam"),
        ("preveja","prevejas","preveja","prevejamos","prevejais","prevejam"),
        ("previsse","previsses","previsse","prevíssemos","prevísseis","previssem"),
        ("previr","previres","previr","previrmos","previrdes","previrem"),
        ("prevê","preveja","prevejamos","prevede","prevejam"),
        ("prevejas","preveja","prevejamos","prevejais","prevejam"),
    ),
    manual("conseguir","to manage/get","ir_irregular",
        ("consigo","consegues","consegue","conseguimos","conseguis","conseguem"),
        ("consegui","conseguiste","conseguiu","conseguimos","conseguistes","conseguiram"),
        ("conseguia","conseguias","conseguia","conseguíamos","conseguíeis","conseguiam"),
        ("conseguira","conseguiras","conseguira","conseguíramos","conseguíreis","conseguiram"),
        ("conseguirei","conseguirás","conseguirá","conseguiremos","conseguireis","conseguirão"),
        ("conseguiria","conseguirias","conseguiria","conseguiríamos","conseguiríeis","conseguiriam"),
        ("consiga","consigas","consiga","consigamos","consigais","consigam"),
        ("conseguisse","conseguisses","conseguisse","conseguíssemos","conseguísseis","conseguissem"),
        ("conseguir","conseguires","conseguir","conseguirmos","conseguirdes","conseguirem"),
        ("consegue","consiga","consigamos","consegui","consigam"),
        ("consigas","consiga","consigamos","consigais","consigam"),
    ),
    manual("perseguir","to pursue","ir_irregular",
        ("persigo","persegues","persegue","perseguimos","perseguis","perseguem"),
        ("persegui","perseguiste","perseguiu","perseguimos","perseguistes","perseguiram"),
        ("perseguia","perseguias","perseguia","perseguíamos","perseguíeis","perseguiam"),
        ("perseguira","perseguiras","perseguira","perseguíramos","perseguíreis","perseguiram"),
        ("perseguirei","perseguirás","perseguirá","perseguiremos","perseguireis","perseguirão"),
        ("perseguiria","perseguirias","perseguiria","perseguiríamos","perseguiríeis","perseguiriam"),
        ("persiga","persigas","persiga","persigamos","persigais","persigam"),
        ("perseguisse","perseguisses","perseguisse","perseguíssemos","perseguísseis","perseguissem"),
        ("perseguir","perseguires","perseguir","perseguirmos","perseguirdes","perseguirem"),
        ("persegue","persiga","persigamos","persegui","persigam"),
        ("persigas","persiga","persigamos","persigais","persigam"),
    ),
    manual("prosseguir","to continue/proceed","ir_irregular",
        ("prossigo","prossegues","prossegue","prosseguimos","prosseguis","prosseguem"),
        ("prossegui","prosseguiste","prosseguiu","prosseguimos","prosseguistes","prosseguiram"),
        ("prosseguia","prosseguias","prosseguia","prosseguíamos","prosseguíeis","prosseguiam"),
        ("prosseguira","prosseguiras","prosseguira","prosseguíramos","prosseguíreis","prosseguiram"),
        ("prosseguirei","prosseguirás","prosseguirá","prosseguiremos","prosseguireis","prosseguirão"),
        ("prosseguiria","prosseguirias","prosseguiria","prosseguiríamos","prosseguiríeis","prosseguiriam"),
        ("prossiga","prossigas","prossiga","prossigamos","prossigais","prossigam"),
        ("prosseguisse","prosseguisses","prosseguisse","prosseguíssemos","prosseguísseis","prosseguissem"),
        ("prosseguir","prosseguires","prosseguir","prosseguirmos","prosseguirdes","prosseguirem"),
        ("prossegue","prossiga","prossigamos","prossegui","prossigam"),
        ("prossigas","prossiga","prossigamos","prossigais","prossigam"),
    ),
    manual("repetir","to repeat","ir_irregular",
        ("repito","repetes","repete","repetimos","repetis","repetem"),
        ("repeti","repetiste","repetiu","repetimos","repetistes","repetiram"),
        ("repetia","repetias","repetia","repetíamos","repetíeis","repetiam"),
        ("repetira","repetiras","repetira","repetíramos","repetíreis","repetiram"),
        ("repetirei","repetirás","repetirá","repetiremos","repetireis","repetirão"),
        ("repetiria","repetirias","repetiria","repetiríamos","repetiríeis","repetiriam"),
        ("repita","repitas","repita","repitamos","repitais","repitam"),
        ("repetisse","repetisses","repetisse","repetíssemos","repetísseis","repetissem"),
        ("repetir","repetires","repetir","repetirmos","repetirdes","repetirem"),
        ("repete","repita","repitamos","repeti","repitam"),
        ("repitas","repita","repitamos","repitais","repitam"),
    ),
    manual("subir","to go up","ir_irregular",
        ("subo","sobes","sobe","subimos","subis","sobem"),
        ("subi","subiste","subiu","subimos","subistes","subiram"),
        ("subia","subias","subia","subíamos","subíeis","subiam"),
        ("subira","subiras","subira","subíramos","subíreis","subiram"),
        ("subirei","subirás","subirá","subiremos","subireis","subirão"),
        ("subiria","subirias","subiria","subiríamos","subiríeis","subiriam"),
        ("suba","subas","suba","subamos","subais","subam"),
        ("subisse","subisses","subisse","subíssemos","subísseis","subissem"),
        ("subir","subires","subir","subirmos","subirdes","subirem"),
        ("sobe","suba","subamos","subi","subam"),
        ("subas","suba","subamos","subais","subam"),
    ),
]

# Count and trim/pad to 250
print(f"Total verbs generated: {len(verbs)}")

# Remove duplicates by infinitive (keep first occurrence)
seen = set()
unique_verbs = []
for v in verbs:
    if v["infinitive"] not in seen:
        seen.add(v["infinitive"])
        unique_verbs.append(v)

print(f"Unique verbs: {len(unique_verbs)}")

# If we have duplicates like ir_regular("subir",...) and manual("subir",...), keep manual
# Already handled above - first occurrence kept. Since ir_regular comes before manual for subir,
# need to re-order. Let's do a second pass keeping the last occurrence instead for manual overrides.
# Actually let's just deduplicate keeping last:
seen2 = {}
for v in verbs:
    seen2[v["infinitive"]] = v
final_verbs = list(seen2.values())
print(f"Final unique verbs (keep last): {len(final_verbs)}")

output_path = r"C:\Code\TestingGround\Android\App2\app\src\main\assets\verbs.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(final_verbs, f, ensure_ascii=False, indent=2)

print(f"Written {len(final_verbs)} verbs to {output_path}")
