package com.example.southkoreatravel.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
fun GeneralInformationScreen(onBack: () -> Unit) {
    ScreenScaffold(title = "General Information", onBack = onBack) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(24.dp)
        ) {
            SectionHeader("Currency")
            BodyText(boldNames("South Korea's currency is the Won (₩, KRW). It comes in large denominations, so don't be alarmed by big numbers on price tags — a ₩15,000 meal is roughly $11, not $15,000.", listOf("Won")))
            BodyText(boldNames("As of September 2026, roughly ₩1,330-1,340 = 1 USD. Against the Israeli Shekel, roughly 1 ILS = ₩470-500 (the rate has moved between about ₩470 and ₩540 per shekel over 2026, so it does shift). These are approximate — check a live converter (Wise, XE, or your bank) close to your travel dates rather than relying on a fixed number.", listOf("Wise", "XE")))
            BodyText(boldNames("Cash is still widely used, especially at markets and small street-food stalls, but international Visa/Mastercard are accepted almost everywhere else, including taxis and convenience stores.", listOf("Visa", "Mastercard")))
            BodyText(boldNames("For the best exchange rate, licensed private money-changers in Myeongdong (Seoul) — names like Daesagwan, Daesin, Ilpumhyang, and GOGO Currency Exchange come up repeatedly — generally beat both bank branches and airport counters. Rates are posted on boards outside so you can compare before going in, and crisp, newer, unfolded US$100 bills tend to get a better rate than worn or older-series notes. A practical approach is to exchange only a small amount at the airport for immediate cash needs, then do the bulk of your exchange in Myeongdong. Bank branches are a safe fallback but usually give a worse rate; ATM withdrawals with a foreign card are also reasonable, especially for smaller amounts.", listOf("Myeongdong", "Daesagwan", "Daesin", "Ilpumhyang", "GOGO Currency Exchange")))
            BodyText(boldNames("Private currency exchange booths in Korea are legally required to register with the financial authorities, and the vast majority of Myeongdong money-changers are properly licensed legitimate businesses, not scams. A legitimate booth will have a posted, up-to-date rate board, will show you the calculation before you commit, and will give you a printed receipt — treat the absence of any of these as a reason to walk away rather than a confirmed sign of a scam on its own.", listOf("Myeongdong")))
            BodyText("Warning signs to actually watch for: a booth off the main tourist strip advertising a rate noticeably better than every neighboring booth (a common lure before hidden \"service fees\" appear at calculation time), refusal to show you the math, pressure to complete the exchange quickly, or no receipt at the end. Korea's customs authorities do periodically crack down on unlicensed exchange operators, so it's worth checking the live official rate (on your phone) before you exchange so you can immediately spot a deal that's too good to be true. And whether you're at an ATM or paying by card, if you're ever asked \"pay in KRW or your home currency,\" always choose KRW — the home-currency option (dynamic currency conversion) applies a worse exchange rate set by the merchant's processor rather than your card network.")

            SectionHeader("Phones, SIMs and eSIMs")
            BodyText(boldNames("Korea has near-universal 4G and 5G coverage nationwide across its three carriers — SK Telecom (SKT), KT, and LG U+ — with 5G mainly running on the n78 (3.5GHz) band for all three. All three also held 28GHz mmWave licenses, but Korean regulators cancelled or shortened most of them in 2022 over missed rollout targets, so mmWave isn't something you'll actually encounter as a tourist — n78 is what matters, and it's what you'll get.", listOf("SK Telecom", "SKT", "KT", "LG U+")))
            BodyText(boldNames("All three carriers sell tourist SIMs and eSIMs directly, and third-party resellers such as EG SIM and WABI SIM (plus general travel platforms) resell the same underlying networks. Physical SIM pickup counters exist at Incheon, Gimpo, and Gimhae (Busan) airports. Global eSIM brands like Airalo also offer a Korea plan, but which local network it rides on — and whether it includes 5G or only 4G — is genuinely inconsistent across sources and may depend on the specific plan, so check the current details for your chosen provider close to your travel dates rather than assuming full 5G access.", listOf("EG SIM", "WABI SIM", "Incheon", "Gimpo", "Gimhae", "Airalo")))
            BodyText(boldNames("The purchase restrictions differ sharply by plan type. Data-only SIMs and eSIMs require no in-person ID or passport check at all — you can buy and activate one entirely online before you even land, which makes them the easiest option if you just need maps and messaging apps. A plan that includes a real Korean phone number for voice calls and texts, by contrast, legally requires passport verification, which typically means either an added online verification step or picking it up in person — some providers even cap how many voice SIMs you can register per passport. If you don't need a local number to call/text, a data-only eSIM is the simplest choice.", listOf("Airalo")))
            BodyText(boldNames("Jeju Island has excellent 4G/5G coverage from all three carriers across Jeju City, Seogwipo, the airport, and major sites — the only real gap is at higher elevation, where signal can fall back to LTE-only or drop out above roughly 1,400m on Hallasan's upper trails.", listOf("Jeju Island", "Jeju City", "Seogwipo", "Hallasan")))

            SectionHeader("Payment in Stores and Restaurants")
            BodyText(boldNames("Beyond T-money (covered above under Getting Around Cities), Cashbee is a similar rechargeable transit card also usable for small retail purchases, sold at convenience stores and subway stations. WOWPASS is specifically aimed at foreign tourists: it combines T-money's transit function with a prepaid Visa/Mastercard-network debit card usable much more broadly for retail, can be loaded in up to 16 currencies, and caps around ₩1,000,000.", listOf("T-money", "Cashbee", "WOWPASS", "Visa", "Mastercard")))
            BodyText(boldNames("Apple Pay launched in Korea in 2023 but remains tied exclusively to Hyundai Card — only Hyundai Card-issued cards can be added to the Wallet — and only works at NFC-capable terminals, which are still a minority of Korean point-of-sale machines. Reported plans for Shinhan Card and KB Kookmin Card to add support had reportedly stalled as of mid-2026 over NFC infrastructure costs. In practice, don't count on Apple Pay working at a random Korean store unless you specifically hold a Hyundai Card — a physical card or cash remains the reliable fallback. Note that T-money was separately added to Apple Wallet in 2025, but that's just for transit fares, not general retail payment.", listOf("Apple Pay", "Hyundai Card", "Shinhan Card", "KB Kookmin Card", "T-money")))
            BodyText(boldNames("Samsung Pay earned its \"works everywhere in Korea\" reputation through MST (magnetic stripe emulation), which let it work on old-style card terminals without needing NFC hardware — but Samsung phones from around the Galaxy S21 (2021) onward dropped MST support and are NFC-only, so a newer Samsung phone can no longer rely on that same universal compatibility. Google Pay, meanwhile, has no official general launch in Korea as of this writing, so it shouldn't be assumed to work as a general payment method here.", listOf("Samsung Pay", "Galaxy S21", "Google Pay")))
            BodyText("As with currency exchange and ATMs, card terminals in Korean stores will sometimes ask whether to charge you in KRW or your home currency — always choose KRW. Accepting the home-currency option triggers dynamic currency conversion, where the merchant's payment processor sets its own exchange rate, typically 3-8% worse than the rate your card network (Visa/Mastercard) would otherwise give you.")

            SectionHeader("Getting Around Cities")
            BodyText("Seoul and Busan both have extensive subway networks (Seoul's is one of the largest in the world), and every city has a dense bus network layered on top — in Seoul, buses are color-coded by role: blue for trunk routes across the city, green for feeder routes to subway stations, red for express routes to satellite cities, and yellow for short circular routes.")
            BodyText(boldNames("Korea's equivalent of Japan's Suica or Icoca is the T-money card — a single rechargeable card that works on the subway, city buses, and many taxis nationwide, so unlike some regional cards in Japan, one T-money card works everywhere in Korea. Buy one at any convenience store (CU, GS25, 7-Eleven, Emart24, Ministop) for a small fee, or get a \"T-money Only for Foreigners\" card at an airport bus counter (about ₩23,500, including ₩20,000 of preloaded credit). Top it up with cash at a convenience store counter or at English-language subway station kiosks; there's also a Mobile T-money app that lets you load it from a foreign Mastercard, Amex, or UnionPay card.", listOf("T-money Only for Foreigners", "Mobile T-money", "T-money", "CU", "GS25", "7-Eleven", "Emart24", "Ministop")))
            BodyText("To pay, simply tap the card on the reader when entering — and importantly, tap again when exiting the subway or getting off the bus, since fares (and free transfers between bus and subway) are calculated based on both taps.")
            BodyText(boldNames("Unlike Japan's Shinkansen, there's no reservation-required size limit for everyday subway or city bus luggage — you can bring a normal suitcase on with you. If you're taking the KTX (Korea's high-speed intercity train) with a large bag, note that carry-on space is limited: the official carry-on guideline is about 50×40×20cm/10kg, though larger suitcases are generally tolerated in the luggage racks and compartments at the end of each car if they fit — just expect those spaces to fill up fast on weekends and holidays.", listOf("Shinkansen", "KTX")))

            SectionHeader("Luggage Forwarding")
            BodyText(boldNames("Korea doesn't have a walk-into-any-shop service as ubiquitous as Japan's Takkyubin, but same-day luggage delivery does exist and is easy to book online in advance. Services like Zimcarry (branded TRIPEASY at Incheon Airport), Goodlugg, and Luggagent operate airport-to-hotel, hotel-to-hotel, and hotel-to-airport delivery at major airports (Incheon, Gimpo, Gimhae, Jeju) and train stations (Seoul Station, Busan Station, and others). Expect to pay roughly ₩15,000-50,000 depending on the route, and to book ahead rather than just dropping a bag off on the spot.", listOf("Takkyubin", "Zimcarry", "TRIPEASY", "Goodlugg", "Luggagent")))

            SectionHeader("Entry Requirements")
            BodyText(boldNames("South Korea normally requires visa-free travelers to pre-register online through K-ETA (Korea Electronic Travel Authorization, at the official site k-eta.go.kr) before flying in. However, Israeli citizens are currently exempt from this K-ETA requirement for tourism — an exemption the Korean government has extended through December 31, 2026 — on top of already being able to visit visa-free for stays of up to 90 days.", listOf("K-ETA")))
            BodyText(boldNames("In practice, this means an Israeli tourist currently does not need to fill in anything online or print a confirmation before flying to Korea. That said, the exemption is temporary and K-ETA is set to become mandatory again for all visa-free travelers from January 1, 2027, so if you're traveling after that date, check k-eta.go.kr again closer to your trip in case the rules have changed. If K-ETA ever is required for you, apply at least 72 hours (ideally a week) before your flight — you'll need your passport, a payment card, an email address, and a recent photo.", listOf("K-ETA")))
        }
    }
}
