package com.example.windowsapp

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import com.example.windowsapp.ui.theme.HackerGreen

@Composable
fun RpcWmiScreen(navController: NavController) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black)
            .verticalScroll(rememberScrollState())
            .padding(horizontal = 24.dp, vertical = 48.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Top
    ) {
        Text(
            text = "RPC AND WMI",
            color = HackerGreen,
            fontFamily = FontFamily.Monospace,
            fontWeight = FontWeight.Bold,
            fontSize = 20.sp,
            textAlign = TextAlign.Center
        )

        Spacer(modifier = Modifier.height(8.dp))

        Text(
            text = "─".repeat(28),
            color = HackerGreen,
            fontFamily = FontFamily.Monospace,
            fontSize = 14.sp
        )

        Spacer(modifier = Modifier.height(24.dp))

        // WHAT IS RPC
        SectionHeader("WHAT IS RPC")
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "RPC (Remote Procedure Call) lets a program call a function in another address " +
            "space — typically another process or another machine — as if it were a local " +
            "function call. Windows RPC implements the DCE/RPC standard (Open Group).\n\n" +
            "Key components:\n" +
            "  • Client stub  — generated code that marshals arguments into a network buffer\n" +
            "  • Server stub  — generated code that unmarshals the buffer and calls your function\n" +
            "  • Runtime      — rpcrt4.dll; manages connections, security, threading\n" +
            "  • Endpoint mapper — port 135; clients ask it which port a given interface is on\n\n" +
            "Transport protocols (protocol sequences):\n" +
            "  ncacn_ip_tcp   — TCP/IP (remote)\n" +
            "  ncacn_np       — named pipes (\\pipe\\...)\n" +
            "  ncalrpc        — ALPC (local only, fastest for same-machine)\n" +
            "  ncacn_http     — RPC over HTTP (firewall-friendly)"
        )

        Spacer(modifier = Modifier.height(16.dp))

        // RUNNING YOUR OWN RPC SERVER
        SectionHeader("RUNNING YOUR OWN RPC SERVER")
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "Step 1 — define the interface in a .idl file and compile with MIDL. " +
            "MIDL generates a header and two C files (client stub, server stub)."
        )
        Spacer(modifier = Modifier.height(8.dp))
        CodeBlock(
            "// myservice.idl\n" +
            "[\n" +
            "    uuid(6BFFD098-A112-3610-9833-46C3F87E345A),\n" +
            "    version(1.0)\n" +
            "]\n" +
            "interface IMyService {\n" +
            "    long Add([in] long a, [in] long b);\n" +
            "    void Shutdown(void);\n" +
            "}"
        )
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "Step 2 — register the interface, choose a transport, and start listening:"
        )
        Spacer(modifier = Modifier.height(8.dp))
        CodeBlock(
            "// Server-side setup\n" +
            "RpcServerUseProtseqEpW(\n" +
            "    L\"ncalrpc\",          // local only (ALPC)\n" +
            "    RPC_C_PROTSEQ_MAX_REQS_DEFAULT,\n" +
            "    L\"MyEndpoint\",       // endpoint name\n" +
            "    NULL);               // security descriptor\n\n" +
            "RpcServerRegisterIfEx(\n" +
            "    IMyService_v1_0_s_ifspec,  // generated by MIDL\n" +
            "    NULL,\n" +
            "    NULL,\n" +
            "    RPC_IF_ALLOW_CALLBACKS_WITH_NO_AUTH,\n" +
            "    RPC_C_LISTEN_MAX_CALLS_DEFAULT,\n" +
            "    NULL);\n\n" +
            "RpcServerListen(\n" +
            "    1,                        // min threads\n" +
            "    RPC_C_LISTEN_MAX_CALLS_DEFAULT,\n" +
            "    FALSE);                   // block until server stops"
        )
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "The server implementation just fills in the function bodies declared in the " +
            "IDL — the stubs handle all marshaling automatically."
        )

        Spacer(modifier = Modifier.height(16.dp))

        // CALLING FROM ANOTHER PROCESS
        SectionHeader("CALLING FROM ANOTHER PROCESS")
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "The client uses a binding handle to connect to the server. For local ALPC:"
        )
        Spacer(modifier = Modifier.height(8.dp))
        CodeBlock(
            "RPC_WSTR bindingString = NULL;\n" +
            "RPC_BINDING_HANDLE hBinding = NULL;\n\n" +
            "// Build \"ncalrpc:[MyEndpoint]\"\n" +
            "RpcStringBindingComposeW(\n" +
            "    NULL,            // object UUID (NULL = any)\n" +
            "    L\"ncalrpc\",\n" +
            "    NULL,            // network address\n" +
            "    L\"MyEndpoint\",\n" +
            "    NULL,            // network options\n" +
            "    &bindingString);\n\n" +
            "RpcBindingFromStringBindingW(bindingString, &hBinding);\n" +
            "RpcStringFreeW(&bindingString);\n\n" +
            "// Now call as if it were local — stub handles marshaling\n" +
            "long result = Add(hBinding, 3, 4);   // returns 7\n\n" +
            "RpcBindingFree(&hBinding);"
        )
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "For TCP across machines, replace ncalrpc with ncacn_ip_tcp and supply the " +
            "server's IP address as the network address argument."
        )

        Spacer(modifier = Modifier.height(16.dp))

        // RPC SECURITY
        SectionHeader("RPC SECURITY")
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "The server can require authentication and control which callers are allowed:\n\n" +
            "  RpcServerRegisterAuthInfoW — registers an authentication service (e.g., " +
            "RPC_C_AUTHN_WINNT for NTLM, RPC_C_AUTHN_GSS_KERBEROS for Kerberos)\n\n" +
            "Inside a server function, you can impersonate the caller to do access checks " +
            "under the caller's token:\n"
        )
        Spacer(modifier = Modifier.height(8.dp))
        CodeBlock(
            "long Add(handle_t hBinding, long a, long b) {\n" +
            "    RpcImpersonateClient(hBinding);  // switch to caller's token\n" +
            "    // ... access-check protected resources ...\n" +
            "    RpcRevertToSelf();               // drop impersonation\n" +
            "    return a + b;\n" +
            "}"
        )

        Spacer(modifier = Modifier.height(16.dp))

        // WHAT IS WMI
        SectionHeader("WHAT IS WMI")
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "WMI (Windows Management Instrumentation) is Microsoft's implementation of " +
            "WBEM (Web-Based Enterprise Management), which is based on the CIM (Common " +
            "Information Model) standard from DMTF.\n\n" +
            "Architecture:\n" +
            "  • winmgmt service — the WMI service (host: svchost)\n" +
            "  • CIMOM repository — persistent schema/instance store (C:\\Windows\\System32\\wbem\\Repository)\n" +
            "  • WMI providers   — COM servers that expose management data; can be in-process " +
            "                      or out-of-process\n\n" +
            "Consumers query WMI via COM:\n" +
            "  IWbemLocator::ConnectServer() → IWbemServices\n" +
            "  IWbemServices::ExecQuery() with WQL (WMI Query Language, SQL-like)\n\n" +
            "Example WQL query:\n"
        )
        Spacer(modifier = Modifier.height(8.dp))
        CodeBlock(
            "SELECT Name, ProcessId, CommandLine\n" +
            "FROM Win32_Process\n" +
            "WHERE Name = 'notepad.exe'"
        )
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "PowerShell exposes WMI through Get-WmiObject (legacy) and Get-CimInstance " +
            "(modern, uses DCOM or WinRM transport)."
        )

        Spacer(modifier = Modifier.height(16.dp))

        // HOW RPC AND WMI RELATE
        SectionHeader("HOW RPC AND WMI RELATE")
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "WMI remote access is built on top of DCOM (Distributed COM). DCOM uses RPC " +
            "as its wire transport:\n\n" +
            "  Remote WMI client\n" +
            "       ↓\n" +
            "  IWbemLocator::ConnectServer(L\"\\\\remotehost\\\\root\\\\cimv2\")\n" +
            "       ↓\n" +
            "  DCOM activation — contacts port 135 (RPC endpoint mapper) on remotehost\n" +
            "       ↓\n" +
            "  Endpoint mapper returns dynamic port for the WMI service\n" +
            "       ↓\n" +
            "  RPC connection to dynamic port, marshaled COM calls flow over it\n\n" +
            "Locally, WMI uses ALPC/LRPC instead of TCP — no port 135 involved for " +
            "same-machine access. The abstraction is transparent; the COM proxy/stub code " +
            "chooses the transport automatically."
        )

        Spacer(modifier = Modifier.height(16.dp))

        // WINDOWS SERVICES USING RPC
        SectionHeader("WINDOWS SERVICES USING RPC")
        Spacer(modifier = Modifier.height(8.dp))
        CodeBlock(
            "Print Spooler  (spoolsv.exe)   — print job management\n" +
            "LSASS          (lsass.exe)      — authentication, LSA policy, SAM\n" +
            "Task Scheduler (svchost)        — job creation, ITaskService interface\n" +
            "Remote Registry (svchost)       — registry access over the network\n" +
            "Server service  (svchost)       — SMB share management (srvsvc pipe)\n" +
            "DNS Client      (svchost)       — DNS resolver control interface\n" +
            "DHCP Client     (svchost)       — IP address management\n" +
            "EventLog        (svchost)       — event subscription and forwarding\n" +
            "SCM             (services.exe)  — service control (sc.exe talks RPC)\n" +
            "WinRM           (svchost)       — remote management (uses HTTP transport)"
        )
        Spacer(modifier = Modifier.height(8.dp))
        BodyText(
            "Most built-in Windows management interfaces — anything reachable from a remote " +
            "machine or via a named pipe — are RPC interfaces underneath."
        )

        Spacer(modifier = Modifier.height(16.dp))

        // WINDOWS SERVICES USING WMI
        SectionHeader("WINDOWS SERVICES USING WMI")
        Spacer(modifier = Modifier.height(8.dp))
        CodeBlock(
            "Windows Firewall         — exposes firewall rules via ROOT\\StandardCimv2\n" +
            "SCCM / Intune            — inventory and deployment use WMI extensively\n" +
            "Windows Defender         — anti-malware events via ROOT\\Microsoft\\Windows\\Defender\n" +
            "WMI-based event subs      — attackers abuse __EventFilter + __EventConsumer\n" +
            "                           for persistence (fileless, survives reboots)\n" +
            "PowerShell DSC           — Desired State Configuration uses WMI providers\n" +
            "Device Manager internals — hardware info via Win32_PnPEntity, Win32_DiskDrive\n\n" +
            "Common provider namespaces:\n" +
            "  ROOT\\CIMV2             — core OS (Win32_Process, Win32_Service, Win32_OS)\n" +
            "  ROOT\\WMI               — kernel/driver tracing (EventTrace, MSAcpi_...)\n" +
            "  ROOT\\SecurityCenter2   — antivirus/firewall product detection"
        )

        Spacer(modifier = Modifier.height(32.dp))

        HackerButton("< BACK") { navController.popBackStack() }
    }
}
