package com.example.arabicapp.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

@Composable
fun PrepositionsScreen() {
    Column(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
            .padding(horizontal = 16.dp, vertical = 8.dp)
    ) {
        PrepSectionHeader("Conjunctions")
        PrepBodyText("These words link phrases and clauses together.")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("AND — و (w)")
        PrepBodyText("• Written as a prefix attached to the next word")
        PrepBodyText("• رحت وشفته — ruḥt w-shifto — I went and saw him")
        PrepBodyText("• بياكل وبيشرب — byakol w-byishrab — he eats and drinks")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("OR — أو (aw) / ولا (wella)")
        PrepBodyText("• أو (aw) — more formal, used in questions and choices")
        PrepBodyText("• ولا (wella) — very common in spoken Palestinian Arabic")
        PrepBodyText("• بدك شاي ولا قهوة؟ — biddak shai wella 'ahwe? — do you want tea or coffee?")
        PrepBodyText("• تيجي معي أو لأ؟ — tiji ma'i aw la? — are you coming with me or not?")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("NOT — مش (mish) / ما...ش (ma...sh)")
        PrepBodyText("• مش (mish) negates nouns, adjectives, non-verb phrases")
        PrepBodyText("• ما...ش wraps around a verb for verb negation")
        PrepBodyText("• مش كبير — mish kbir — not big")
        PrepBodyText("• ما بعرفش — ma ba'refsh — I don't know")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("WITHOUT — بلا (bala) / بدون (bidun)")
        PrepBodyText("• بلا (bala) — colloquial Palestinian")
        PrepBodyText("• بدون (bidun) — slightly more formal, also used")
        PrepBodyText("• بلا سكر — bala sukkar — without sugar")
        PrepBodyText("• بدون أكل — bidun akl — without food")
        PrepBodyText("• رحت بلاه — ruḥt balah — I went without him")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("THEREFORE / SO — لهيك (la-hek) / يعني (ya'ni)")
        PrepBodyText("• لهيك (la-hek) — therefore, so (because of that)")
        PrepBodyText("• يعني (ya'ni) — literally 'it means', used as 'so/therefore/basically'")
        PrepBodyText("• ما كانش عنده وقت, لهيك ما جاش — ma kan 'ando wa'it, la-hek ma jash — he didn't have time, so he didn't come")
        PrepBodyText("• يعني بدنا نروح بكير — ya'ni bidna nruḥ bikir — so we need to go early")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("EVEN THOUGH / ALTHOUGH — مع إنو (ma' inno) / رغم إنو (raghm inno)")
        PrepBodyText("• مع إنو (ma' inno) — even though, despite the fact that")
        PrepBodyText("• رغم إنو (raghm inno) — despite the fact that (slightly stronger)")
        PrepBodyText("• جاء مع إنو كان تعبان — ja ma' inno kan ta'ban — he came even though he was tired")
        PrepBodyText("• رغم إنو ما بعرف, بحكي — raghm inno ma ba'ref, bḥki — even though I don't know, I'll speak")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("WHILE — وهم (w-humm) / بينما (beinma)")
        PrepBodyText("• وهم + subject + verb = 'while [subject] was doing'")
        PrepBodyText("• وهم نايمين, جا — w-humm naymeen, ja — while they were sleeping, he came")
        PrepBodyText("• وهي تحكي, كنت بفكر — w-hiyye tḥki, kunt bfakker — while she was talking, I was thinking")

        PrepSectionHeader("Prepositions of Time")
        PrepBodyText("AFTER — بعد (ba'd)")
        PrepBodyText("• بعد الأكل — ba'd il-akl — after eating")
        PrepBodyText("• بعد بكرا — ba'd bukra — the day after tomorrow")
        PrepBodyText("• بعد ما يرجع — ba'd ma yirja' — after he comes back")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("BEFORE — قبل ('abl)")
        PrepBodyText("• قبل ما نروح — 'abl ma nruḥ — before we go")
        PrepBodyText("• قبل الضهر — 'abl iḍ-ḍuhr — before noon")
        PrepBodyText("• قبل سنتين — 'abl santein — two years ago (lit. 'before two years')")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("UNTIL — لغايت (lghayt) / على ما ('ala ma)")
        PrepBodyText("• لغايت بكرا — lghayt bukra — until tomorrow")
        PrepBodyText("• على ما يرجع — 'ala ma yirja' — until he comes back")
        PrepBodyText("• لغايت هلق — lghayt halla' — until now")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("WHEN — لمّا (lamma) / وقت (wa'it ma)")
        PrepBodyText("• لمّا (lamma) — when (at the time that)")
        PrepBodyText("• لمّا جيت, كان نايم — lamma jiit, kan naym — when you came, he was sleeping")
        PrepBodyText("• وقت ما بدي حاجة, بسألك — wa'it ma biddi ḥaje, bas'alak — when I need something, I'll ask you")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("FROM [TIME] TO [TIME] — من...لـ (min...la)")
        PrepBodyText("• من التسعة لاثنعش — min it-tis'a la-itnashr — from nine to twelve")
        PrepBodyText("• من الصبح لالليل — min iṣ-ṣubuḥ lal-leil — from morning to night")
        PrepBodyText("• من اثنين لاربعة — min itnein la-arba'a — from two to four")

        PrepSectionHeader("Prepositions of Movement & Direction")
        PrepBodyText("TO (place/direction) — لـ (la-) / على ('ala)")
        PrepBodyText("• لـ (la-) — to [a place], towards, for a person")
        PrepBodyText("• على ('ala) — onto, towards, used with movement verbs")
        PrepBodyText("• رحت لبيته — ruḥt la-beto — I went to his house")
        PrepBodyText("• طلعت على جبل — ṭil'it 'ala jabal — I went up to the mountain")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("FROM — من (min) / من عند (min 'ind)")
        PrepBodyText("• من (min) — from [a place]")
        PrepBodyText("• من عند (min 'ind) — from [a person], from someone's place")
        PrepBodyText("• جيت من الشغل — jiit min ish-shughul — I came from work")
        PrepBodyText("• جيت من عند أمي — jiit min 'ind immi — I came from my mother's place")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("TO WHERE — لوين (la-wein)")
        PrepBodyText("• رايح لوين؟ — rayyiḥ la-wein? — where are you going?")
        PrepBodyText("• لوين بدك تروح؟ — la-wein biddak truḥ? — where do you want to go?")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("TO WHOM — لمين (la-miin)")
        PrepBodyText("• حكيت لمين؟ — ḥakiit la-miin? — who did you speak to?")
        PrepBodyText("• بعتلها لمين؟ — ba'ittilha la-miin? — who did you send it to?")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("FROM WHOM — من مين (min miin) / من عند مين (min 'ind miin)")
        PrepBodyText("• أخدتو من مين؟ — akhatto min miin? — who did you get it from?")
        PrepBodyText("• جيت من عند مين؟ — jiit min 'ind miin? — whose place are you coming from?")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("WHOM / WHO — مين (miin)")
        PrepBodyText("• مين حكالك؟ — miin ḥaka-lak? — who told you?")
        PrepBodyText("• شفت مين؟ — shift miin? — who did you see?")

        PrepSectionHeader("Prepositions of Place")
        PrepBodyText("INSIDE — جوا (jawwa) / بالداخل (bil-dakhil)")
        PrepBodyText("• جوا البيت — jawwa l-beit — inside the house")
        PrepBodyText("• هو جوا — huwa jawwa — he is inside")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("OUTSIDE — برا (barra)")
        PrepBodyText("• هي برا — hiyye barra — she is outside")
        PrepBodyText("• برا البلد — barra l-balad — outside the city")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("ON / ABOVE — فوق (foo') / على ('ala)")
        PrepBodyText("• على الطاولة — 'ala ṭ-ṭawle — on the table")
        PrepBodyText("• فوق السقف — foo' is-sa'if — above/on the roof")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("BELOW / UNDER — تحت (taht)")
        PrepBodyText("• تحت الكرسي — taht il-kursi — under the chair")
        PrepBodyText("• تحت الأرض — taht il-arḍ — underground / below the ground")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("IN — في (fi) / بـ (b-)")
        PrepBodyText("• في البيت — fil-beit — in the house")
        PrepBodyText("• بالقاعة — bil-qa'a — in the hall")
        PrepBodyText("• في إيدو — fi ido — in his hand")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("BY / NEXT TO — جنب (janb) / عند ('and)")
        PrepBodyText("• جنب الباب — janb il-bab — next to the door")
        PrepBodyText("• وقف عندو — wi'if 'ando — stood next to him / by him")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("NEAR — قريب من ('arib min)")
        PrepBodyText("• قريب من البيت — 'arib min il-beit — near the house")
        PrepBodyText("• هو قريب منك — huwa 'arib minnak — he is near you")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("FAR FROM / AWAY FROM — بعيد عن (b'id 'an)")
        PrepBodyText("• بعيد عن البلد — b'id 'an il-balad — far from the city")
        PrepBodyText("• ابعد عن هون — ib'id 'an hawn — get away from here / move away from here")
        PrepBodyText("• بعيد عنك — b'id 'annak — away from you / far from you")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("TOWARDS — نحو (naḥwa) / لعند (la-'and) / لجهة (la-jihet)")
        PrepBodyText("• نحو (naḥwa) — towards [a direction], slightly formal")
        PrepBodyText("• لعند (la-'and) — towards a person, going in someone's direction")
        PrepBodyText("• لجهة (la-jihet) — in the direction of [a place]")
        PrepBodyText("• تمشى نحو الباب — tamsha naḥwa l-bab — walk towards the door")
        PrepBodyText("• جا لعندي — ja la-'andi — he came towards me")
        PrepBodyText("• روح لجهة الشمال — ruḥ la-jihet ish-shmal — go towards the north")

        PrepSectionHeader("With a Person / From a Person")
        PrepBodyText("WITH — مع (ma')")
        PrepBodyText("• جيت معه — jiit ma'o — I came with him")
        PrepBodyText("• بدي أحكي معك — biddi aḥki ma'ak — I want to talk with you")
        PrepBodyText("• مع بعض — ma' ba'aḍ — together (lit. 'with each other')")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("FROM A PERSON — من (min) / من عند (min 'ind)")
        PrepBodyText("• أخدت الكتاب منه — akhatt il-ktab minno — I took the book from him")
        PrepBodyText("• سمعت من عند أهلها — simi't min 'ind ahilha — I heard from her family")
        PrepBodyText("• هاي رسالة منك؟ — hayde risale minnak? — is this a message from you?")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("TO A PERSON — لـ (la-) / عند ('and)")
        PrepBodyText("• بعتلو رسالة — ba'ittilo risale — I sent him a message")
        PrepBodyText("• قلتلها — 'ultilha — I told her (lit. 'I said to her')")
        PrepBodyText("• عنده مشكلة — 'ando mushkile — he has a problem (lit. 'at him a problem')")

        PrepSectionHeader("For")
        PrepBodyText("FOR — لـ (la-) for benefit; عشان/'ashaan or مشان/mishaan for purpose")
        Spacer(modifier = Modifier.height(4.dp))
        PrepBodyText("BENEFIT — لـ (la-) [doing something on behalf of / for the sake of]")
        PrepBodyText("• عم بشتغل هيك لشغلتي — 'am bishtaghil hayk la-shughilti — I'm doing it this way for my job")
        PrepBodyText("• هاد إلك — had ilak — this is for you")
        PrepBodyText("• عامل هيك لصالحك — 'amil hayk la-ṣaliḥak — doing this for your benefit")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("PURPOSE — عشان ('ashaan) / مشان (mishaan) [so that / in order that]")
        PrepBodyText("• عشان (ashaan) — so that, in order to, because (Palestinian form of أشان)")
        PrepBodyText("• مشان (mishaan) — Palestinian variant of عشان, very common")
        PrepBodyText("• بشتغل كتير مشان يوفر فلوس — bishtaghil ktir mishaan yuwaffir flus — he works a lot in order to save money")
        PrepBodyText("• عشان هيك ما جيت — 'ashaan hek ma jiit — that's why I didn't come (for that reason)")
        PrepBodyText("• مشان تنجح لازم تذاكر — mishaan tinjah lazim tzakir — in order to succeed you need to study")
        Spacer(modifier = Modifier.height(8.dp))
        PrepBodyText("HOPING FOR — متمني على (mitmanni 'ala) / عم بتمنى إنو ('am batmanna inno)")
        PrepBodyText("• عم بتمنى إنو يصير هيك — 'am batmanna inno yiṣir hayk — I'm hoping for this to happen")
        PrepBodyText("• متمني على خبر منك — mitmanni 'ala khabar minnak — hoping to hear from you")
        PrepBodyText("• بتمنى يزبط الموضوع — batmanna yizbuṭ il-mawdu' — hoping for things to work out")

        PrepSectionHeader("Quick Reference")
        PrepBodyText("و (w) — and")
        PrepBodyText("أو (aw) / ولا (wella) — or")
        PrepBodyText("مش (mish) — not (non-verb)")
        PrepBodyText("ما...ش (ma...sh) — not (verb negation)")
        PrepBodyText("بلا (bala) / بدون (bidun) — without")
        PrepBodyText("لهيك (la-hek) — therefore")
        PrepBodyText("مع إنو (ma' inno) — even though")
        PrepBodyText("رغم إنو (raghm inno) — although / despite")
        PrepBodyText("وهم (w-humm) — while (they were...)")
        PrepBodyText("بعد (ba'd) — after")
        PrepBodyText("قبل ('abl) — before")
        PrepBodyText("لغايت (lghayt) / على ما ('ala ma) — until")
        PrepBodyText("لمّا (lamma) — when")
        PrepBodyText("من...لـ (min...la) — from...to")
        PrepBodyText("لـ (la-) — to [place/person]")
        PrepBodyText("من (min) — from")
        PrepBodyText("من عند (min 'ind) — from [a person's place]")
        PrepBodyText("لوين (la-wein) — to where")
        PrepBodyText("لمين (la-miin) — to whom")
        PrepBodyText("من مين (min miin) — from whom")
        PrepBodyText("مين (miin) — who / whom")
        PrepBodyText("جوا (jawwa) — inside")
        PrepBodyText("برا (barra) — outside")
        PrepBodyText("فوق (foo') / على ('ala) — on / above")
        PrepBodyText("تحت (taht) — below / under")
        PrepBodyText("في (fi) / بـ (b-) — in")
        PrepBodyText("جنب (janb) — next to")
        PrepBodyText("قريب من ('arib min) — near")
        PrepBodyText("بعيد عن (b'id 'an) — far from / away from")
        PrepBodyText("نحو (naḥwa) / لجهة (la-jihet) — towards")
        PrepBodyText("مع (ma') — with")
        PrepBodyText("لـ (la-) — for [benefit]")
        PrepBodyText("عشان ('ashaan) / مشان (mishaan) — for [purpose] / so that")

        Spacer(modifier = Modifier.height(24.dp))
    }
}

@Composable
private fun PrepSectionHeader(text: String) {
    Spacer(modifier = Modifier.height(20.dp))
    Text(
        text = text,
        style = MaterialTheme.typography.titleLarge,
        fontWeight = FontWeight.Bold,
        modifier = Modifier.fillMaxWidth()
    )
    Spacer(modifier = Modifier.height(8.dp))
    HorizontalDivider()
    Spacer(modifier = Modifier.height(8.dp))
}

@Composable
private fun PrepBodyText(text: String) {
    Text(
        text = text,
        style = MaterialTheme.typography.bodyMedium,
        modifier = Modifier.padding(vertical = 2.dp)
    )
}
