package com.example.arabicapp.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

@Composable
fun SimpleConjugatedVerbsScreen() {
    Column(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
            .padding(horizontal = 16.dp, vertical = 8.dp)
    ) {
        CVSectionHeader("راح — raH — to go")
        CVBodyText("Hollow verb (root r-w-H). Note: راح is ALSO used as the future particle — context distinguishes the two uses.")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا رحت — ana ruHt — I went")
        CVBodyText("إنت رحت — inta ruHt — you (m) went")
        CVBodyText("إنتِ رحتِ — inti ruHti — you (f) went")
        CVBodyText("هو راح — huwwe raH — he went")
        CVBodyText("هي راحت — hiyye raaHat — she went")
        CVBodyText("إحنا رحنا — iHna ruHna — we went")
        CVBodyText("إنتو رحتو — intu ruHtu — you (pl) went")
        CVBodyText("هم راحو — humme raaHu — they went")
        CVSubHeader("Present")
        CVBodyText("أنا بروح — ana baruH — I go")
        CVBodyText("إنت بتروح — inta btaruH — you (m) go")
        CVBodyText("إنتِ بتروحي — inti btaruHi — you (f) go")
        CVBodyText("هو بيروح — huwwe byiruH — he goes")
        CVBodyText("هي بتروح — hiyye btaruH — she goes")
        CVBodyText("إحنا بنروح — iHna bnaruH — we go")
        CVBodyText("إنتو بتروحو — intu btaruHu — you (pl) go")
        CVBodyText("هم بيروحو — humme byiruHu — they go")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بروح — 'am baruH — I am going")
        CVBodyText("إنت عم بتروح — 'am btaruH — you (m) are going")
        CVBodyText("إنتِ عم بتروحي — 'am btaruHi — you (f) are going")
        CVBodyText("هو عم بيروح — 'am byiruH — he is going")
        CVBodyText("هي عم بتروح — 'am btaruH — she is going")
        CVBodyText("إحنا عم بنروح — 'am bnaruH — we are going")
        CVBodyText("إنتو عم بتروحو — 'am btaruHu — you (pl) are going")
        CVBodyText("هم عم بيروحو — 'am byiruHu — they are going")
        CVSubHeader("Future")
        CVBodyText("أنا راح روح — raH ruH — I will go")
        CVBodyText("إنت راح تروح — raH truH — you (m) will go")
        CVBodyText("إنتِ راح تروحي — raH truHi — you (f) will go")
        CVBodyText("هو راح يروح — raH yiruH — he will go")
        CVBodyText("هي راح تروح — raH truH — she will go")
        CVBodyText("إحنا راح نروح — raH nruH — we will go")
        CVBodyText("إنتو راح تروحو — raH truHu — you (pl) will go")
        CVBodyText("هم راح يروحو — raH yiruHu — they will go")

        CVSectionHeader("جا — ja — to come")
        CVBodyText("Irregular verb. Present stem: yiji.")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا جيت — ana jiit — I came")
        CVBodyText("إنت جيت — inta jiit — you (m) came")
        CVBodyText("إنتِ جيتِ — inti jiiti — you (f) came")
        CVBodyText("هو جا — huwwe ja — he came")
        CVBodyText("هي جات — hiyye jaat — she came")
        CVBodyText("إحنا جينا — iHna jiina — we came")
        CVBodyText("إنتو جيتو — intu jiitu — you (pl) came")
        CVBodyText("هم جاو — humme jaau — they came")
        CVSubHeader("Present")
        CVBodyText("أنا بجي — ana bajji — I come")
        CVBodyText("إنت بتجي — inta btijji — you (m) come")
        CVBodyText("إنتِ بتجي — inti btijji — you (f) come")
        CVBodyText("هو بيجي — huwwe byiji — he comes")
        CVBodyText("هي بتجي — hiyye btiji — she comes")
        CVBodyText("إحنا بنجي — iHna bnjii — we come")
        CVBodyText("إنتو بتجو — intu btiju — you (pl) come")
        CVBodyText("هم بيجو — humme byiju — they come")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بجي — 'am bajji — I am coming")
        CVBodyText("إنت عم بتجي — 'am btijji — you (m) are coming")
        CVBodyText("إنتِ عم بتجي — 'am btijji — you (f) are coming")
        CVBodyText("هو عم بيجي — 'am byiji — he is coming")
        CVBodyText("هي عم بتجي — 'am btiji — she is coming")
        CVBodyText("إحنا عم بنجي — 'am bnjii — we are coming")
        CVBodyText("إنتو عم بتجو — 'am btiju — you (pl) are coming")
        CVBodyText("هم عم بيجو — 'am byiju — they are coming")
        CVSubHeader("Future")
        CVBodyText("أنا راح جي — raH ji — I will come")
        CVBodyText("إنت راح تجي — raH tiji — you (m) will come")
        CVBodyText("إنتِ راح تجي — raH tiji — you (f) will come")
        CVBodyText("هو راح يجي — raH yiji — he will come")
        CVBodyText("هي راح تجي — raH tiji — she will come")
        CVBodyText("إحنا راح نجي — raH nji — we will come")
        CVBodyText("إنتو راح تجو — raH tiju — you (pl) will come")
        CVBodyText("هم راح يجو — raH yiju — they will come")

        CVSectionHeader("اشتغل — shtaghal — to work")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا اشتغلت — ana shtaghalt — I worked")
        CVBodyText("إنت اشتغلت — inta shtaghalt — you (m) worked")
        CVBodyText("إنتِ اشتغلتِ — inti shtaghalti — you (f) worked")
        CVBodyText("هو اشتغل — huwwe shtaghal — he worked")
        CVBodyText("هي اشتغلت — hiyye shtaghalat — she worked")
        CVBodyText("إحنا اشتغلنا — iHna shtaghalna — we worked")
        CVBodyText("إنتو اشتغلتو — intu shtaghaltu — you (pl) worked")
        CVBodyText("هم اشتغلو — humme shtaghalu — they worked")
        CVSubHeader("Present")
        CVBodyText("أنا بشتغل — ana bishtaghil — I work")
        CVBodyText("إنت بتشتغل — inta btishtaghil — you (m) work")
        CVBodyText("إنتِ بتشتغلي — inti btishtaghli — you (f) work")
        CVBodyText("هو بيشتغل — huwwe byishtaghil — he works")
        CVBodyText("هي بتشتغل — hiyye btishtaghil — she works")
        CVBodyText("إحنا بنشتغل — iHna bnishtaghil — we work")
        CVBodyText("إنتو بتشتغلو — intu btishtaghlu — you (pl) work")
        CVBodyText("هم بيشتغلو — humme byishtaghlu — they work")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بشتغل — 'am bishtaghil — I am working")
        CVBodyText("إنت عم بتشتغل — 'am btishtaghil — you (m) are working")
        CVBodyText("إنتِ عم بتشتغلي — 'am btishtaghli — you (f) are working")
        CVBodyText("هو عم بيشتغل — 'am byishtaghil — he is working")
        CVBodyText("هي عم بتشتغل — 'am btishtaghil — she is working")
        CVBodyText("إحنا عم بنشتغل — 'am bnishtaghil — we are working")
        CVBodyText("إنتو عم بتشتغلو — 'am btishtaghlu — you (pl) are working")
        CVBodyText("هم عم بيشتغلو — 'am byishtaghlu — they are working")
        CVSubHeader("Future")
        CVBodyText("أنا راح اشتغل — raH ashtaghil — I will work")
        CVBodyText("إنت راح تشتغل — raH tishtaghil — you (m) will work")
        CVBodyText("إنتِ راح تشتغلي — raH tishtaghli — you (f) will work")
        CVBodyText("هو راح يشتغل — raH yishtaghil — he will work")
        CVBodyText("هي راح تشتغل — raH tishtaghil — she will work")
        CVBodyText("إحنا راح نشتغل — raH nishtaghil — we will work")
        CVBodyText("إنتو راح تشتغلو — raH tishtaghlu — you (pl) will work")
        CVBodyText("هم راح يشتغلو — raH yishtaghlu — they will work")

        CVSectionHeader("عرف — 'araf — to know / to find out")
        CVBodyText("In Arabic, عرف covers both \"to know\" and \"to find out / learn\" — they are the same verb.")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا عرفت — ana 'araft — I knew / found out")
        CVBodyText("إنت عرفت — inta 'araft — you (m) knew")
        CVBodyText("إنتِ عرفتِ — inti 'arafti — you (f) knew")
        CVBodyText("هو عرف — huwwe 'araf — he knew")
        CVBodyText("هي عرفت — hiyye 'arafat — she knew")
        CVBodyText("إحنا عرفنا — iHna 'arafna — we knew")
        CVBodyText("إنتو عرفتو — intu 'araftu — you (pl) knew")
        CVBodyText("هم عرفو — humme 'arafu — they knew")
        CVSubHeader("Present")
        CVBodyText("أنا بعرف — ana ba'rif — I know")
        CVBodyText("إنت بتعرف — inta bta'rif — you (m) know")
        CVBodyText("إنتِ بتعرفي — inti bta'rfi — you (f) know")
        CVBodyText("هو بيعرف — huwwe byi'rif — he knows")
        CVBodyText("هي بتعرف — hiyye bta'rif — she knows")
        CVBodyText("إحنا بنعرف — iHna bna'rif — we know")
        CVBodyText("إنتو بتعرفو — intu bta'rifu — you (pl) know")
        CVBodyText("هم بيعرفو — humme byi'rifu — they know")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بعرف — 'am ba'rif — I am finding out")
        CVBodyText("إنت عم بتعرف — 'am bta'rif — you (m) are finding out")
        CVBodyText("إنتِ عم بتعرفي — 'am bta'rfi — you (f) are finding out")
        CVBodyText("هو عم بيعرف — 'am byi'rif — he is finding out")
        CVBodyText("هي عم بتعرف — 'am bta'rif — she is finding out")
        CVBodyText("إحنا عم بنعرف — 'am bna'rif — we are finding out")
        CVBodyText("إنتو عم بتعرفو — 'am bta'rifu — you (pl) are finding out")
        CVBodyText("هم عم بيعرفو — 'am byi'rifu — they are finding out")
        CVSubHeader("Future")
        CVBodyText("أنا راح اعرف — raH a'rif — I will know / find out")
        CVBodyText("إنت راح تعرف — raH ta'rif — you (m) will know")
        CVBodyText("إنتِ راح تعرفي — raH ta'rfi — you (f) will know")
        CVBodyText("هو راح يعرف — raH yi'rif — he will know")
        CVBodyText("هي راح تعرف — raH ta'rif — she will know")
        CVBodyText("إحنا راح نعرف — raH na'rif — we will know")
        CVBodyText("إنتو راح تعرفو — raH ta'rifu — you (pl) will know")
        CVBodyText("هم راح يعرفو — raH yi'rifu — they will know")

        CVSectionHeader("أكل — akal — to eat")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا أكلت — ana akalt — I ate")
        CVBodyText("إنت أكلت — inta akalt — you (m) ate")
        CVBodyText("إنتِ أكلتِ — inti akalti — you (f) ate")
        CVBodyText("هو أكل — huwwe akal — he ate")
        CVBodyText("هي أكلت — hiyye akalit — she ate")
        CVBodyText("إحنا أكلنا — iHna akalna — we ate")
        CVBodyText("إنتو أكلتو — intu akaltu — you (pl) ate")
        CVBodyText("هم أكلو — humme akalu — they ate")
        CVSubHeader("Present")
        CVBodyText("أنا باكل — ana baakol — I eat")
        CVBodyText("إنت بتاكل — inta btaakol — you (m) eat")
        CVBodyText("إنتِ بتاكلي — inti btaakli — you (f) eat")
        CVBodyText("هو بياكل — huwwe byaakol — he eats")
        CVBodyText("هي بتاكل — hiyye btaakol — she eats")
        CVBodyText("إحنا بناكل — iHna bnaakol — we eat")
        CVBodyText("إنتو بتاكلو — intu btaaklu — you (pl) eat")
        CVBodyText("هم بياكلو — humme byaaklu — they eat")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم باكل — 'am baakol — I am eating")
        CVBodyText("إنت عم بتاكل — 'am btaakol — you (m) are eating")
        CVBodyText("إنتِ عم بتاكلي — 'am btaakli — you (f) are eating")
        CVBodyText("هو عم بياكل — 'am byaakol — he is eating")
        CVBodyText("هي عم بتاكل — 'am btaakol — she is eating")
        CVBodyText("إحنا عم بناكل — 'am bnaakol — we are eating")
        CVBodyText("إنتو عم بتاكلو — 'am btaaklu — you (pl) are eating")
        CVBodyText("هم عم بياكلو — 'am byaaklu — they are eating")
        CVSubHeader("Future")
        CVBodyText("أنا راح آكل — raH aakol — I will eat")
        CVBodyText("إنت راح تاكل — raH taakol — you (m) will eat")
        CVBodyText("إنتِ راح تاكلي — raH taakli — you (f) will eat")
        CVBodyText("هو راح ياكل — raH yaakol — he will eat")
        CVBodyText("هي راح تاكل — raH taakol — she will eat")
        CVBodyText("إحنا راح ناكل — raH naakol — we will eat")
        CVBodyText("إنتو راح تاكلو — raH taaklu — you (pl) will eat")
        CVBodyText("هم راح ياكلو — raH yaaklu — they will eat")

        CVSectionHeader("شرب — shirib — to drink")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا شربت — ana shiribt — I drank")
        CVBodyText("إنت شربت — inta shiribt — you (m) drank")
        CVBodyText("إنتِ شربتِ — inti shiribti — you (f) drank")
        CVBodyText("هو شرب — huwwe shirib — he drank")
        CVBodyText("هي شربت — hiyye shirbit — she drank")
        CVBodyText("إحنا شربنا — iHna shiribna — we drank")
        CVBodyText("إنتو شربتو — intu shiribtu — you (pl) drank")
        CVBodyText("هم شربو — humme shirbu — they drank")
        CVSubHeader("Present")
        CVBodyText("أنا بشرب — ana bishrab — I drink")
        CVBodyText("إنت بتشرب — inta btishrab — you (m) drink")
        CVBodyText("إنتِ بتشربي — inti btishrabi — you (f) drink")
        CVBodyText("هو بيشرب — huwwe byishrab — he drinks")
        CVBodyText("هي بتشرب — hiyye btishrab — she drinks")
        CVBodyText("إحنا بنشرب — iHna bnishrab — we drink")
        CVBodyText("إنتو بتشربو — intu btishrabu — you (pl) drink")
        CVBodyText("هم بيشربو — humme byishrabu — they drink")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بشرب — 'am bishrab — I am drinking")
        CVBodyText("إنت عم بتشرب — 'am btishrab — you (m) are drinking")
        CVBodyText("إنتِ عم بتشربي — 'am btishrabi — you (f) are drinking")
        CVBodyText("هو عم بيشرب — 'am byishrab — he is drinking")
        CVBodyText("هي عم بتشرب — 'am btishrab — she is drinking")
        CVBodyText("إحنا عم بنشرب — 'am bnishrab — we are drinking")
        CVBodyText("إنتو عم بتشربو — 'am btishrabu — you (pl) are drinking")
        CVBodyText("هم عم بيشربو — 'am byishrabu — they are drinking")
        CVSubHeader("Future")
        CVBodyText("أنا راح اشرب — raH ashrab — I will drink")
        CVBodyText("إنت راح تشرب — raH tishrab — you (m) will drink")
        CVBodyText("إنتِ راح تشربي — raH tishrabi — you (f) will drink")
        CVBodyText("هو راح يشرب — raH yishrab — he will drink")
        CVBodyText("هي راح تشرب — raH tishrab — she will drink")
        CVBodyText("إحنا راح نشرب — raH nishrab — we will drink")
        CVBodyText("إنتو راح تشربو — raH tishrabu — you (pl) will drink")
        CVBodyText("هم راح يشربو — raH yishrabu — they will drink")

        CVSectionHeader("دفع — dafa' — to pay")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا دفعت — ana dafa't — I paid")
        CVBodyText("إنت دفعت — inta dafa't — you (m) paid")
        CVBodyText("إنتِ دفعتِ — inti dafa'ti — you (f) paid")
        CVBodyText("هو دفع — huwwe dafa' — he paid")
        CVBodyText("هي دفعت — hiyye dafa'at — she paid")
        CVBodyText("إحنا دفعنا — iHna dafa'na — we paid")
        CVBodyText("إنتو دفعتو — intu dafa'tu — you (pl) paid")
        CVBodyText("هم دفعو — humme dafa'u — they paid")
        CVSubHeader("Present")
        CVBodyText("أنا بدفع — ana bidfa' — I pay")
        CVBodyText("إنت بتدفع — inta btidfa' — you (m) pay")
        CVBodyText("إنتِ بتدفعي — inti btidfa'i — you (f) pay")
        CVBodyText("هو بيدفع — huwwe byidfa' — he pays")
        CVBodyText("هي بتدفع — hiyye btidfa' — she pays")
        CVBodyText("إحنا بندفع — iHna bnidfa' — we pay")
        CVBodyText("إنتو بتدفعو — intu btidfa'u — you (pl) pay")
        CVBodyText("هم بيدفعو — humme byidfa'u — they pay")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بدفع — 'am bidfa' — I am paying")
        CVBodyText("إنت عم بتدفع — 'am btidfa' — you (m) are paying")
        CVBodyText("إنتِ عم بتدفعي — 'am btidfa'i — you (f) are paying")
        CVBodyText("هو عم بيدفع — 'am byidfa' — he is paying")
        CVBodyText("هي عم بتدفع — 'am btidfa' — she is paying")
        CVBodyText("إحنا عم بندفع — 'am bnidfa' — we are paying")
        CVBodyText("إنتو عم بتدفعو — 'am btidfa'u — you (pl) are paying")
        CVBodyText("هم عم بيدفعو — 'am byidfa'u — they are paying")
        CVSubHeader("Future")
        CVBodyText("أنا راح ادفع — raH adfa' — I will pay")
        CVBodyText("إنت راح تدفع — raH tidfa' — you (m) will pay")
        CVBodyText("إنتِ راح تدفعي — raH tidfa'i — you (f) will pay")
        CVBodyText("هو راح يدفع — raH yidfa' — he will pay")
        CVBodyText("هي راح تدفع — raH tidfa' — she will pay")
        CVBodyText("إحنا راح ندفع — raH nidfa' — we will pay")
        CVBodyText("إنتو راح تدفعو — raH tidfa'u — you (pl) will pay")
        CVBodyText("هم راح يدفعو — raH yidfa'u — they will pay")

        CVSectionHeader("شاف — shaaf — to look / to see")
        CVBodyText("Hollow verb (root sh-y-f). Covers both \"to see\" and \"to look at\" in everyday Palestinian speech.")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا شفت — ana shift — I saw / looked")
        CVBodyText("إنت شفت — inta shift — you (m) saw")
        CVBodyText("إنتِ شفتِ — inti shifti — you (f) saw")
        CVBodyText("هو شاف — huwwe shaaf — he saw")
        CVBodyText("هي شافت — hiyye shaafat — she saw")
        CVBodyText("إحنا شفنا — iHna shifna — we saw")
        CVBodyText("إنتو شفتو — intu shiftu — you (pl) saw")
        CVBodyText("هم شافو — humme shaafu — they saw")
        CVSubHeader("Present")
        CVBodyText("أنا بشوف — ana bishuf — I see / look")
        CVBodyText("إنت بتشوف — inta btishuf — you (m) see")
        CVBodyText("إنتِ بتشوفي — inti btishufi — you (f) see")
        CVBodyText("هو بيشوف — huwwe byishuf — he sees")
        CVBodyText("هي بتشوف — hiyye btishuf — she sees")
        CVBodyText("إحنا بنشوف — iHna bnishuf — we see")
        CVBodyText("إنتو بتشوفو — intu btishufu — you (pl) see")
        CVBodyText("هم بيشوفو — humme byishufu — they see")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بشوف — 'am bishuf — I am watching / looking")
        CVBodyText("إنت عم بتشوف — 'am btishuf — you (m) are watching")
        CVBodyText("إنتِ عم بتشوفي — 'am btishufi — you (f) are watching")
        CVBodyText("هو عم بيشوف — 'am byishuf — he is watching")
        CVBodyText("هي عم بتشوف — 'am btishuf — she is watching")
        CVBodyText("إحنا عم بنشوف — 'am bnishuf — we are watching")
        CVBodyText("إنتو عم بتشوفو — 'am btishufu — you (pl) are watching")
        CVBodyText("هم عم بيشوفو — 'am byishufu — they are watching")
        CVSubHeader("Future")
        CVBodyText("أنا راح اشوف — raH ashuuf — I will see / look")
        CVBodyText("إنت راح تشوف — raH tshuuf — you (m) will see")
        CVBodyText("إنتِ راح تشوفي — raH tshuufi — you (f) will see")
        CVBodyText("هو راح يشوف — raH yishuuf — he will see")
        CVBodyText("هي راح تشوف — raH tshuuf — she will see")
        CVBodyText("إحنا راح نشوف — raH nshuuf — we will see")
        CVBodyText("إنتو راح تشوفو — raH tshuufu — you (pl) will see")
        CVBodyText("هم راح يشوفو — raH yishuufu — they will see")

        CVSectionHeader("حكى — Haka — to speak / to talk")
        CVBodyText("Final-y verb: you (f) present form is the same as you (m) — no extra -i added.")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا حكيت — ana Hakeet — I spoke")
        CVBodyText("إنت حكيت — inta Hakeet — you (m) spoke")
        CVBodyText("إنتِ حكيتِ — inti Hakeeti — you (f) spoke")
        CVBodyText("هو حكى — huwwe Haka — he spoke")
        CVBodyText("هي حكت — hiyye Hakit — she spoke")
        CVBodyText("إحنا حكينا — iHna Hakeena — we spoke")
        CVBodyText("إنتو حكيتو — intu Hakeetu — you (pl) spoke")
        CVBodyText("هم حكو — humme Haku — they spoke")
        CVSubHeader("Present")
        CVBodyText("أنا بحكي — ana baHki — I speak")
        CVBodyText("إنت بتحكي — inta btaHki — you (m) speak")
        CVBodyText("إنتِ بتحكي — inti btaHki — you (f) speak  ← same as masculine")
        CVBodyText("هو بيحكي — huwwe byaHki — he speaks")
        CVBodyText("هي بتحكي — hiyye btaHki — she speaks")
        CVBodyText("إحنا بنحكي — iHna bnaHki — we speak")
        CVBodyText("إنتو بتحكو — intu btaHku — you (pl) speak")
        CVBodyText("هم بيحكو — humme byaHku — they speak")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بحكي — 'am baHki — I am talking")
        CVBodyText("إنت عم بتحكي — 'am btaHki — you (m) are talking")
        CVBodyText("إنتِ عم بتحكي — 'am btaHki — you (f) are talking")
        CVBodyText("هو عم بيحكي — 'am byaHki — he is talking")
        CVBodyText("هي عم بتحكي — 'am btaHki — she is talking")
        CVBodyText("إحنا عم بنحكي — 'am bnaHki — we are talking")
        CVBodyText("إنتو عم بتحكو — 'am btaHku — you (pl) are talking")
        CVBodyText("هم عم بيحكو — 'am byaHku — they are talking")
        CVSubHeader("Future")
        CVBodyText("أنا راح احكي — raH aHki — I will speak")
        CVBodyText("إنت راح تحكي — raH taHki — you (m) will speak")
        CVBodyText("إنتِ راح تحكي — raH taHki — you (f) will speak")
        CVBodyText("هو راح يحكي — raH yaHki — he will speak")
        CVBodyText("هي راح تحكي — raH taHki — she will speak")
        CVBodyText("إحنا راح نحكي — raH naHki — we will speak")
        CVBodyText("إنتو راح تحكو — raH taHku — you (pl) will speak")
        CVBodyText("هم راح يحكو — raH yaHku — they will speak")

        CVSectionHeader("تفرّج — tfarraj — to watch")
        CVBodyText("Form V verb. Used specifically for watching something (TV, a game, a show). Use with على: تفرّج على = to watch.")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا تفرّجت — ana tfarrajt — I watched")
        CVBodyText("إنت تفرّجت — inta tfarrajt — you (m) watched")
        CVBodyText("إنتِ تفرّجتِ — inti tfarrajti — you (f) watched")
        CVBodyText("هو تفرّج — huwwe tfarraj — he watched")
        CVBodyText("هي تفرّجت — hiyye tfarrajat — she watched")
        CVBodyText("إحنا تفرّجنا — iHna tfarrajna — we watched")
        CVBodyText("إنتو تفرّجتو — intu tfarrajtu — you (pl) watched")
        CVBodyText("هم تفرّجو — humme tfarraju — they watched")
        CVSubHeader("Present")
        CVBodyText("أنا بتفرّج — ana bitfarraj — I watch")
        CVBodyText("إنت بتتفرّج — inta btitfarraj — you (m) watch")
        CVBodyText("إنتِ بتتفرّجي — inti btitfarraji — you (f) watch")
        CVBodyText("هو بيتفرّج — huwwe byitfarraj — he watches")
        CVBodyText("هي بتتفرّج — hiyye btitfarraj — she watches")
        CVBodyText("إحنا بنتفرّج — iHna bnitfarraj — we watch")
        CVBodyText("إنتو بتتفرّجو — intu btitfarraju — you (pl) watch")
        CVBodyText("هم بيتفرّجو — humme byitfarraju — they watch")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بتفرّج — 'am bitfarraj — I am watching")
        CVBodyText("إنت عم بتتفرّج — 'am btitfarraj — you (m) are watching")
        CVBodyText("إنتِ عم بتتفرّجي — 'am btitfarraji — you (f) are watching")
        CVBodyText("هو عم بيتفرّج — 'am byitfarraj — he is watching")
        CVBodyText("هي عم بتتفرّج — 'am btitfarraj — she is watching")
        CVBodyText("إحنا عم بنتفرّج — 'am bnitfarraj — we are watching")
        CVBodyText("إنتو عم بتتفرّجو — 'am btitfarraju — you (pl) are watching")
        CVBodyText("هم عم بيتفرّجو — 'am byitfarraju — they are watching")
        CVSubHeader("Future")
        CVBodyText("أنا راح اتفرّج — raH atfarraj — I will watch")
        CVBodyText("إنت راح تتفرّج — raH titfarraj — you (m) will watch")
        CVBodyText("إنتِ راح تتفرّجي — raH titfarraji — you (f) will watch")
        CVBodyText("هو راح يتفرّج — raH yitfarraj — he will watch")
        CVBodyText("هي راح تتفرّج — raH titfarraj — she will watch")
        CVBodyText("إحنا راح نتفرّج — raH nitfarraj — we will watch")
        CVBodyText("إنتو راح تتفرّجو — raH titfarraju — you (pl) will watch")
        CVBodyText("هم راح يتفرّجو — raH yitfarraju — they will watch")

        CVSectionHeader("سمع — simi' — to listen / to hear")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا سمعت — ana simi't — I listened / heard")
        CVBodyText("إنت سمعت — inta simi't — you (m) heard")
        CVBodyText("إنتِ سمعتِ — inti simi'ti — you (f) heard")
        CVBodyText("هو سمع — huwwe simi' — he heard")
        CVBodyText("هي سمعت — hiyye simi'at — she heard")
        CVBodyText("إحنا سمعنا — iHna simi'na — we heard")
        CVBodyText("إنتو سمعتو — intu simi'tu — you (pl) heard")
        CVBodyText("هم سمعو — humme simi'u — they heard")
        CVSubHeader("Present")
        CVBodyText("أنا بسمع — ana bisma' — I listen / hear")
        CVBodyText("إنت بتسمع — inta btisma' — you (m) listen")
        CVBodyText("إنتِ بتسمعي — inti btisma'i — you (f) listen")
        CVBodyText("هو بيسمع — huwwe byisma' — he listens")
        CVBodyText("هي بتسمع — hiyye btisma' — she listens")
        CVBodyText("إحنا بنسمع — iHna bnisma' — we listen")
        CVBodyText("إنتو بتسمعو — intu btisma'u — you (pl) listen")
        CVBodyText("هم بيسمعو — humme byisma'u — they listen")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بسمع — 'am bisma' — I am listening")
        CVBodyText("إنت عم بتسمع — 'am btisma' — you (m) are listening")
        CVBodyText("إنتِ عم بتسمعي — 'am btisma'i — you (f) are listening")
        CVBodyText("هو عم بيسمع — 'am byisma' — he is listening")
        CVBodyText("هي عم بتسمع — 'am btisma' — she is listening")
        CVBodyText("إحنا عم بنسمع — 'am bnisma' — we are listening")
        CVBodyText("إنتو عم بتسمعو — 'am btisma'u — you (pl) are listening")
        CVBodyText("هم عم بيسمعو — 'am byisma'u — they are listening")
        CVSubHeader("Future")
        CVBodyText("أنا راح اسمع — raH asma' — I will listen")
        CVBodyText("إنت راح تسمع — raH tisma' — you (m) will listen")
        CVBodyText("إنتِ راح تسمعي — raH tisma'i — you (f) will listen")
        CVBodyText("هو راح يسمع — raH yisma' — he will listen")
        CVBodyText("هي راح تسمع — raH tisma' — she will listen")
        CVBodyText("إحنا راح نسمع — raH nisma' — we will listen")
        CVBodyText("إنتو راح تسمعو — raH tisma'u — you (pl) will listen")
        CVBodyText("هم راح يسمعو — raH yisma'u — they will listen")

        CVSectionHeader("قرأ — 'ara — to read")
        CVBodyText("The letter ق (qaf) → glottal stop in Palestinian Arabic, so قرأ sounds like 'ara (not qara). This is the standard urban Palestinian pronunciation.")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا قرأت — ana 'areet — I read")
        CVBodyText("إنت قرأت — inta 'areet — you (m) read")
        CVBodyText("إنتِ قرأتِ — inti 'areeti — you (f) read")
        CVBodyText("هو قرأ — huwwe 'ara — he read")
        CVBodyText("هي قرأت — hiyye 'arat — she read")
        CVBodyText("إحنا قرأنا — iHna 'areena — we read")
        CVBodyText("إنتو قرأتو — intu 'areetu — you (pl) read")
        CVBodyText("هم قرأو — humme 'arau — they read")
        CVSubHeader("Present")
        CVBodyText("أنا بقرأ — ana bi'ra — I read")
        CVBodyText("إنت بتقرأ — inta bti'ra — you (m) read")
        CVBodyText("إنتِ بتقرأي — inti bti'rai — you (f) read")
        CVBodyText("هو بيقرأ — huwwe byi'ra — he reads")
        CVBodyText("هي بتقرأ — hiyye bti'ra — she reads")
        CVBodyText("إحنا بنقرأ — iHna bni'ra — we read")
        CVBodyText("إنتو بتقرأو — intu bti'rau — you (pl) read")
        CVBodyText("هم بيقرأو — humme byi'rau — they read")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بقرأ — 'am bi'ra — I am reading")
        CVBodyText("إنت عم بتقرأ — 'am bti'ra — you (m) are reading")
        CVBodyText("إنتِ عم بتقرأي — 'am bti'rai — you (f) are reading")
        CVBodyText("هو عم بيقرأ — 'am byi'ra — he is reading")
        CVBodyText("هي عم بتقرأ — 'am bti'ra — she is reading")
        CVBodyText("إحنا عم بنقرأ — 'am bni'ra — we are reading")
        CVBodyText("إنتو عم بتقرأو — 'am bti'rau — you (pl) are reading")
        CVBodyText("هم عم بيقرأو — 'am byi'rau — they are reading")
        CVSubHeader("Future")
        CVBodyText("أنا راح اقرأ — raH a'ra — I will read")
        CVBodyText("إنت راح تقرأ — raH ti'ra — you (m) will read")
        CVBodyText("إنتِ راح تقرأي — raH ti'rai — you (f) will read")
        CVBodyText("هو راح يقرأ — raH yi'ra — he will read")
        CVBodyText("هي راح تقرأ — raH ti'ra — she will read")
        CVBodyText("إحنا راح نقرأ — raH ni'ra — we will read")
        CVBodyText("إنتو راح تقرأو — raH ti'rau — you (pl) will read")
        CVBodyText("هم راح يقرأو — raH yi'rau — they will read")

        CVSectionHeader("كتب — katab — to write")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا كتبت — ana katabt — I wrote")
        CVBodyText("إنت كتبت — inta katabt — you (m) wrote")
        CVBodyText("إنتِ كتبتِ — inti katabti — you (f) wrote")
        CVBodyText("هو كتب — huwwe katab — he wrote")
        CVBodyText("هي كتبت — hiyye katabit — she wrote")
        CVBodyText("إحنا كتبنا — iHna katabna — we wrote")
        CVBodyText("إنتو كتبتو — intu katabtu — you (pl) wrote")
        CVBodyText("هم كتبو — humme katabu — they wrote")
        CVSubHeader("Present")
        CVBodyText("أنا بكتب — ana buktub — I write")
        CVBodyText("إنت بتكتب — inta btiktib — you (m) write")
        CVBodyText("إنتِ بتكتبي — inti btiktibi — you (f) write")
        CVBodyText("هو بيكتب — huwwe byiktib — he writes")
        CVBodyText("هي بتكتب — hiyye btiktib — she writes")
        CVBodyText("إحنا بنكتب — iHna bniktib — we write")
        CVBodyText("إنتو بتكتبو — intu btiktibu — you (pl) write")
        CVBodyText("هم بيكتبو — humme byiktibu — they write")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم بكتب — 'am buktub — I am writing")
        CVBodyText("إنت عم بتكتب — 'am btiktib — you (m) are writing")
        CVBodyText("إنتِ عم بتكتبي — 'am btiktibi — you (f) are writing")
        CVBodyText("هو عم بيكتب — 'am byiktib — he is writing")
        CVBodyText("هي عم بتكتب — 'am btiktib — she is writing")
        CVBodyText("إحنا عم بنكتب — 'am bniktib — we are writing")
        CVBodyText("إنتو عم بتكتبو — 'am btiktibu — you (pl) are writing")
        CVBodyText("هم عم بيكتبو — 'am byiktibu — they are writing")
        CVSubHeader("Future")
        CVBodyText("أنا راح اكتب — raH aktib — I will write")
        CVBodyText("إنت راح تكتب — raH tiktib — you (m) will write")
        CVBodyText("إنتِ راح تكتبي — raH tiktibi — you (f) will write")
        CVBodyText("هو راح يكتب — raH yiktib — he will write")
        CVBodyText("هي راح تكتب — raH tiktib — she will write")
        CVBodyText("إحنا راح نكتب — raH niktib — we will write")
        CVBodyText("إنتو راح تكتبو — raH tiktibu — you (pl) will write")
        CVBodyText("هم راح يكتبو — raH yiktibu — they will write")

        CVSectionHeader("رجع — raja' — to return")
        Spacer(modifier = Modifier.height(6.dp))
        CVSubHeader("Past")
        CVBodyText("أنا رجعت — ana raja't — I returned")
        CVBodyText("إنت رجعت — inta raja't — you (m) returned")
        CVBodyText("إنتِ رجعتِ — inti raja'ti — you (f) returned")
        CVBodyText("هو رجع — huwwe raja' — he returned")
        CVBodyText("هي رجعت — hiyye raja'at — she returned")
        CVBodyText("إحنا رجعنا — iHna raja'na — we returned")
        CVBodyText("إنتو رجعتو — intu raja'tu — you (pl) returned")
        CVBodyText("هم رجعو — humme raja'u — they returned")
        CVSubHeader("Present")
        CVBodyText("أنا برجع — ana birja' — I return")
        CVBodyText("إنت بترجع — inta btirja' — you (m) return")
        CVBodyText("إنتِ بترجعي — inti btirja'i — you (f) return")
        CVBodyText("هو بيرجع — huwwe byirja' — he returns")
        CVBodyText("هي بترجع — hiyye btirja' — she returns")
        CVBodyText("إحنا بنرجع — iHna bnirja' — we return")
        CVBodyText("إنتو بترجعو — intu btirja'u — you (pl) return")
        CVBodyText("هم بيرجعو — humme byirja'u — they return")
        CVSubHeader("Present Continuous")
        CVBodyText("أنا عم برجع — 'am birja' — I am returning")
        CVBodyText("إنت عم بترجع — 'am btirja' — you (m) are returning")
        CVBodyText("إنتِ عم بترجعي — 'am btirja'i — you (f) are returning")
        CVBodyText("هو عم بيرجع — 'am byirja' — he is returning")
        CVBodyText("هي عم بترجع — 'am btirja' — she is returning")
        CVBodyText("إحنا عم بنرجع — 'am bnirja' — we are returning")
        CVBodyText("إنتو عم بترجعو — 'am btirja'u — you (pl) are returning")
        CVBodyText("هم عم بيرجعو — 'am byirja'u — they are returning")
        CVSubHeader("Future")
        CVBodyText("أنا راح ارجع — raH arja' — I will return")
        CVBodyText("إنت راح ترجع — raH tirja' — you (m) will return")
        CVBodyText("إنتِ راح ترجعي — raH tirja'i — you (f) will return")
        CVBodyText("هو راح يرجع — raH yirja' — he will return")
        CVBodyText("هي راح ترجع — raH tirja' — she will return")
        CVBodyText("إحنا راح نرجع — raH nirja' — we will return")
        CVBodyText("إنتو راح ترجعو — raH tirja'u — you (pl) will return")
        CVBodyText("هم راح يرجعو — raH yirja'u — they will return")

        CVSectionHeader("كان — kaan — to be")
        CVBodyText("Special verb. In the present tense, Arabic has NO verb for \"am / is / are\" — the present copula is zero. You simply say: أنا تعبان (ana ta'ban) = I am tired, هو طالب (huwwe Talib) = he is a student.")
        Spacer(modifier = Modifier.height(4.dp))
        CVBodyText("For \"there is / there are\" use في (fi): في ناس هون (fi naas hon) = there are people here.")
        Spacer(modifier = Modifier.height(4.dp))
        CVBodyText("Present Continuous of \"to be\" = N/A (\"is being\" is not used in Arabic.)")
        Spacer(modifier = Modifier.height(8.dp))
        CVSubHeader("Past")
        CVBodyText("أنا كنت — ana kunt — I was")
        CVBodyText("إنت كنت — inta kunt — you (m) were")
        CVBodyText("إنتِ كنتِ — inti kunti — you (f) were")
        CVBodyText("هو كان — huwwe kaan — he was")
        CVBodyText("هي كانت — hiyye kaanat — she was")
        CVBodyText("إحنا كنّا — iHna kunna — we were")
        CVBodyText("إنتو كنتو — intu kuntu — you (pl) were")
        CVBodyText("هم كانو — humme kaanu — they were")
        CVSubHeader("Future")
        CVBodyText("أنا راح كون — raH kuun — I will be")
        CVBodyText("إنت راح تكون — raH tkuun — you (m) will be")
        CVBodyText("إنتِ راح تكوني — raH tkuuni — you (f) will be")
        CVBodyText("هو راح يكون — raH yikuun — he will be")
        CVBodyText("هي راح تكون — raH tkuun — she will be")
        CVBodyText("إحنا راح نكون — raH nkuun — we will be")
        CVBodyText("إنتو راح تكونو — raH tkuunu — you (pl) will be")
        CVBodyText("هم راح يكونو — raH yikuunu — they will be")

        Spacer(modifier = Modifier.height(24.dp))
    }
}

@Composable
private fun CVSectionHeader(text: String) {
    Spacer(modifier = Modifier.height(20.dp))
    Text(
        text = text,
        style = MaterialTheme.typography.titleLarge,
        fontWeight = FontWeight.Bold,
        modifier = Modifier.fillMaxWidth()
    )
    Spacer(modifier = Modifier.height(8.dp))
    HorizontalDivider()
    Spacer(modifier = Modifier.height(8.dp))
}

@Composable
private fun CVSubHeader(text: String) {
    Spacer(modifier = Modifier.height(8.dp))
    Text(
        text = text,
        style = MaterialTheme.typography.bodyMedium,
        fontWeight = FontWeight.Bold,
        fontStyle = FontStyle.Italic,
        modifier = Modifier.fillMaxWidth().padding(vertical = 2.dp)
    )
}

@Composable
private fun CVBodyText(text: String) {
    Text(
        text = text,
        style = MaterialTheme.typography.bodyMedium,
        modifier = Modifier.padding(vertical = 2.dp)
    )
}
